CREATE TABLE BI_PATH 
    ("PROCESS_TYPE_ID" VARCHAR2(50 BYTE), 
    "PRODUCT_CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
    "FOLDER" VARCHAR2(50 BYTE), 
    "PATH" VARCHAR2(1000 BYTE), 
    CONSTRAINT "BI_PATH_UNIQUE" UNIQUE ("PROCESS_TYPE_ID", "PRODUCT_CODE")
    );