CREATE TABLE DOCUMENT
   (	ID VARCHAR2(80 BYTE) NOT NULL,
	DOCUMENT_INFO_ID VARCHAR2(100 BYTE) NOT NULL,
	PROCESS_INSTANCE_ID VARCHAR2(100 BYTE) NOT NULL,
	NAME VARCHAR2(200 BYTE) NOT NULL,
	CATEGORY VARCHAR2(100 BYTE) NOT NULL,
	SUB_CATEGORY VARCHAR2(100 BYTE) NOT NULL,
    REFERENCE VARCHAR2(1000 BYTE) NOT NULL,
    SOURCE VARCHAR2(50 BYTE) NOT NULL,
    CONSTRAINT DOCUMENT_PK PRIMARY KEY (ID)
   );

-- ALTER TABLE DOCUMENT
-- MODIFY NAME VARCHAR2(200 BYTE);