--------------------------------------------------------
--  File created - Saturday-January-15-2022
--------------------------------------------------------


-- CREATE SEQUENCE LOAN_CONTRACT_REQUEST_ID
--     INCREMENT BY 1
--     START WITH 1
--     NOMAXVALUE
--     NOCYCLE
--     CACHE 50;


CREATE TABLE LOAN_CONTRACT_PROCESS_REQUEST (
   PROCESS_INSTANCE_ID VARCHAR(50) NOT NULL PRIMARY KEY,
   LOAN_CONTRACT_ID VARCHAR(50) UNIQUE,
   LOAN_CONTRACT_TYPE VARCHAR(50) NOT NULL,
   LOAN_ACCOUNT VARCHAR(50),
   LOAN_AMOUNT NUMBER,
   CREATED_DATE DATE NOT NULL,
   ASSIGNED_USER_ID VARCHAR(50) NOT NULL,
   GROUP_ID VARCHAR(50) NOT NULL,
   TENANT_ID VARCHAR(25),
   STATE VARCHAR(20),
   CIF_NUMBER VARCHAR2(50 BYTE,
   PRODUCT_DESCRIPTION VARCHAR2(75 BYTE)
);

CREATE TABLE LOAN_CONTRACT_PARAMETER(
    PROCESS_INSTANCE_ID VARCHAR(50) NOT NULL,
    DEF_KEY VARCHAR(50) NOT NULL,
    PARAMETER_VALUE CLOB NOT NULL,
    PARAMETER_VALUE_TYPE VARCHAR(20),
    PARAMETER_ENTITY_TYPE VARCHAR(20)
);


-- SELECT CURRENT_DATE, SESSIONTIMEZONE FROM DUAL;
