--------------------------------------------------------
--  ERIN ORGANIZATION SALARY TABLE
--------------------------------------------------------
CREATE TABLE ERIN_ORG_SALARY
   (
    ORG_REQUEST_ID VARCHAR2(50 BYTE) NOT NULL,
	PROCESS_TYPE_ID VARCHAR2(50 BYTE) NOT NULL,
	BRANCH_ID VARCHAR2(4 BYTE) NOT NULL,

	CONTRACT_NUM VARCHAR2(50 BYTE),
    REG_NUMBER VARCHAR2(50 BYTE),
	COUNTRY_REG_NUMBER VARCHAR2(50 BYTE),

    CONTRACT_ORG_NAME VARCHAR2(255 BYTE),
	REGISTERED_ORG_NAME VARCHAR2(255 BYTE),

	OP_TYPE_ID VARCHAR2(10 BYTE),
    OP_TYPE_DESCRIPTION VARCHAR2(255 BYTE),

    ORG_TYPE NUMBER(1),
    MODIFIED_DATE DATE,

    MODIFIED_USER_ID VARCHAR2(255 BYTE),
    STATE VARCHAR2(255 BYTE),

    ACCOUNT_NUMBER VARCHAR2(10 BYTE),
    EMP_COUNT NUMBER(20),

    IS_SALARY_LOAN NUMBER(1),
    HAS_CONTRACT NUMBER(1),

    SPECIAL_CONDITION NCLOB,

    CONSTRAINT ERIN_ORG_SALARY_PK1 PRIMARY KEY (ORG_REQUEST_ID)
   );