--------------------------------------------------------
--  ERIN ORGANIZATION LEASING TABLE
--------------------------------------------------------
CREATE TABLE ERIN_ORG_LEASING
   (
    ORG_REQUEST_ID VARCHAR2(50 BYTE) NOT NULL,
	PROCESS_TYPE_ID VARCHAR2(50 BYTE) NOT NULL,
	BRANCH_ID VARCHAR2(4 BYTE) NOT NULL,

	CONTRACT_NUM VARCHAR2(50 BYTE),
    REG_NUMBER VARCHAR2(50 BYTE),
    COUNTRY_REG_NUMBER VARCHAR2(255 BYTE),

    FULL_NAME VARCHAR2(255 BYTE),
    FIRST_NAME VARCHAR2(255 BYTE),
	LAST_NAME VARCHAR2(255 BYTE),

	COLLABORATOR_TYPE VARCHAR2(50 BYTE),
    MODIFIED_DATE DATE,

    MODIFIED_USER_ID VARCHAR2(255 BYTE),
    STATE VARCHAR2(255 BYTE),

    CITY VARCHAR2(255 BYTE),
    DISTRICT VARCHAR2(255 BYTE),
    QUARTER VARCHAR2(255 BYTE),

    ADDRESS VARCHAR2(255 BYTE),
    PHONE VARCHAR2(100 BYTE),
    FAX VARCHAR2(255 BYTE),
    EMAIL VARCHAR2(100 BYTE),

    CONSTRAINT ERIN_ORG_LEASING_PK1 PRIMARY KEY (ORG_REQUEST_ID)
   );