--------------------------------------------------------
--  ERIN CONTRACT INFO TABLE OF SALARY ORGANIZATION
--------------------------------------------------------
CREATE TABLE ERIN_CONTRACT_INFO_SALARY
  (
     ORG_REQUEST_ID               VARCHAR2(50 BYTE) NOT NULL,
     CONTRACT_NUM             VARCHAR2(50 BYTE) NOT NULL,

     TERM_YEAR                CHAR(2 CHAR) DEFAULT '1',
     LEAKAGE                  NUMBER(18, 2),
     ORG_RANK                 VARCHAR2(255 BYTE),

     INT_RATE_COND            CHAR(2 CHAR) DEFAULT 'ST',
     KEY_EMP_INT_RATE_MONTHLY NUMBER(18, 2),

     MAX_INT_RATE             NUMBER(18, 2),
     MIN_INT_RATE             NUMBER(18, 2),

     SALARY_TRANS_FEE         NUMBER DEFAULT 1,
     SALARY_COUNT_MONTHLY     CHAR(1 CHAR) DEFAULT '2',

     SALARY_FIRST_DAY         CHAR(2 CHAR) DEFAULT '11',
     SALARY_SECOND_DAY        CHAR(2 CHAR) DEFAULT '25',

     CREATED_DATE             TIMESTAMP(6),
     END_DATE                 TIMESTAMP(6),

     CREATED_USER_ID          VARCHAR2(50 BYTE) NOT NULL,
     CREATED_USER_NAME        VARCHAR2(100 BYTE),

     LAST_UPDATED_USER_ID     VARCHAR2(50 BYTE) NOT NULL,
     LAST_UPDATED_USER_NAME   VARCHAR2(100 BYTE),

     APPROVED_USER_ID         VARCHAR2(50 BYTE),
     APPROVED_USER_NAME       VARCHAR2(100 BYTE),

     REL_EMP_NAME             VARCHAR2(255 BYTE),
     REL_EMP_PHONE            VARCHAR2(255 BYTE),

     CREATED_AT               TIMESTAMP(6) NOT NULL,
     UPDATED_AT               TIMESTAMP(6) NOT NULL,

     MODIFIED_NUM             VARCHAR2(50 BYTE) NOT NULL,
     IS_LATEST                CHAR(1 CHAR) DEFAULT 'N',
     SPECIAL_CONDITION        NCLOB,

     CONSTRAINT ERIN_CONTRACT_INFO_SALARY_PK1 PRIMARY KEY (ORG_REQUEST_ID, CONTRACT_NUM)
  );