CREATE TABLE PROCESS
   (	PROCESS_INSTANCE_ID VARCHAR2(50 BYTE) NOT NULL,
	STARTED_DATE DATE NOT NULL,
	FINISHED_DATE DATE,
    CONSTRAINT PROCESS_PK PRIMARY KEY (PROCESS_INSTANCE_ID)
   );

   CREATE TABLE PROCESS_PARAMETER
   (	PROCESS_INSTANCE_ID VARCHAR2(50 BYTE) NOT NULL,
	PARAMETER_NAME VARCHAR2(100 BYTE) NOT NULL,
	PARAMETER_VALUE VARCHAR2(4000 BYTE) NOT NULL,
	PARAMETER_DATA_TYPE VARCHAR2(50 BYTE) NOT NULL,
	PARAMETER_ENTITY_TYPE VARCHAR2(50 BYTE) NOT NULL,
    CONSTRAINT PROCESS_PARAMETER_PK PRIMARY KEY (PROCESS_INSTANCE_ID, PARAMETER_NAME, PARAMETER_ENTITY_TYPE)
   );

  CREATE TABLE PROCESS_LARGE_PARAMETER
   (
    PROCESS_INSTANCE_ID VARCHAR2(50 BYTE) NOT NULL,
	PARAMETER_NAME VARCHAR2(200 BYTE) NOT NULL,
	PARAMETER_VALUE CLOB NOT NULL,
	PARAMETER_DATA_TYPE VARCHAR2(150 BYTE) NOT NULL,
	PARAMETER_ENTITY_TYPE VARCHAR2(150 BYTE) NOT NULL,
    CONSTRAINT PROCESS_LARGE_PARAMETER_PK PRIMARY KEY (PROCESS_INSTANCE_ID, PARAMETER_NAME)
   );


ALTER TABLE PROCESS_PARAMETER
MODIFY PARAMETER_NAME VARCHAR2(100 BYTE);
