CREATE TABLE ERIN_BPMS_TASK_FORM_RELATION
(
    TASK_DEFINITION_ID VARCHAR2(75 BYTE) NOT NULL,
    FORM_VALUE CLOB NOT NULL,
    ENTITY VARCHAR2(25 BYTE) NOT NULL,
    CONSTRAINT ERIN_BPMS_TASK_FORM_RELATION_PK PRIMARY KEY ( TASK_DEFINITION_ID )
);
