
 CREATE TABLE AIM_MEMBERSHIP
   (	MEMBERSHIP_ID VARCHAR2(50 BYTE) NOT NULL,
	USER_ID VARCHAR2(50 BYTE) NOT NULL,
	GROUP_ID VARCHAR2(50 BYTE) NOT NULL,
	ROLE_ID VARCHAR2(50 BYTE) NOT NULL,
	TENANT_ID VARCHAR2(50 BYTE) NOT NULL,
    CONSTRAINT AIM_MEMBERSHIP_PK PRIMARY KEY (MEMBERSHIP_ID),
    CONSTRAINT AIM_MEMBERSHIP_CONSTRAINT UNIQUE (USER_ID, GROUP_ID, ROLE_ID, TENANT_ID)
   );

CREATE TABLE AIM_USER
   (	USER_ID VARCHAR2(50 BYTE) NOT NULL,
	TENANT_ID VARCHAR2(50 BYTE) NOT NULL,
    PASSWORD VARCHAR2(50 BYTE) NOT NULL,
	FIRST_NAME VARCHAR2(50 BYTE),
	LAST_NAME VARCHAR2(50 BYTE),
	DISPLAY_NAME VARCHAR2(50 BYTE),
	EMAIL VARCHAR2(50 BYTE),
	PHONE_NUMBER VARCHAR2(50 BYTE),
    CONSTRAINT AIM_USER_PK PRIMARY KEY (USER_ID)
   );

CREATE TABLE AIM_ROLE
   (	ROLE_ID VARCHAR2(50 BYTE) NOT NULL,
	TENANT_ID VARCHAR2(50 BYTE) NOT NULL,
	NAME VARCHAR2(100 BYTE) NOT NULL,
    CONSTRAINT AIM_ROLE_PK PRIMARY KEY (ROLE_ID)
   );


CREATE TABLE AIM_ROLE_PERMISSION
   (	ROLE_ID VARCHAR2(50 BYTE) NOT NULL,
	PERMISSION_ID VARCHAR2(50 BYTE) NOT NULL,
    CONSTRAINT AIM_ROLE_PERMISSION_PK PRIMARY KEY (ROLE_ID, PERMISSION_ID)
   );

CREATE TABLE AIM_GROUP
   (	ID VARCHAR2(50 BYTE) NOT NULL,
	TENANT_ID VARCHAR2(50 BYTE) NOT NULL,
    PARENT_ID VARCHAR2(50 BYTE),
    NAME VARCHAR2(70 BYTE),
    NTH_SIBLING NUMBER NOT NULL,
    CONSTRAINT AIM_GROUP_PK PRIMARY KEY (ID)
   );

CREATE TABLE AIM_GROUP_PARENT_CHILD
   (	PARENT_ID VARCHAR2(50 BYTE) NOT NULL,
	CHILD_ID VARCHAR2(50 BYTE) NOT NULL,
    CONSTRAINT AIM_GROUP_PARENT_CHILD_PK PRIMARY KEY (PARENT_ID, CHILD_ID)
   );
