package mn.erin.bpm.domain.ohs.xac.util;

import java.util.List;

import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.Assert;
import org.junit.Test;

public class CollateralNewCoreUtilTest
{
  private final String collateralCodeResponse = "{\n"
      + "    \"Source\": \"COR\",\n"
      + "    \"Function\": \"GetcColtrlCode\",\n"
      + "    \"RequestId\": \"2021052110232077\",\n"
      + "    \"UserId\": \"DEVTESTS\",\n"
      + "    \"RequestType\": \"A\",\n"
      + "    \"Status\": \"SUCCESS\",\n"
      + "    \"SecurityCode\": \"4A2B51D53BF42D465894ED9EA84A22FF\",\n"
      + "    \"Response\": [\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BC01\",\n"
      + "            \"ColtrlDesc\": \"Япон суудлын автомашин\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL1\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BC02\",\n"
      + "            \"ColtrlDesc\": \"Солонгос суудлын машин\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL1\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BC03\",\n"
      + "            \"ColtrlDesc\": \"Америк суудлын автомашин\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL1\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BC04\",\n"
      + "            \"ColtrlDesc\": \"Герман суудлын автомашин\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL1\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BC05\",\n"
      + "            \"ColtrlDesc\": \"Орос суудлын автомашин\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL1\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BC06\",\n"
      + "            \"ColtrlDesc\": \"Бусад улсын суудлын машин\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL1\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BT01\",\n"
      + "            \"ColtrlDesc\": \"Япон ачааны автомашин\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL1\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BT02\",\n"
      + "            \"ColtrlDesc\": \"Солонгос ачааны автомашин\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL1\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BT03\",\n"
      + "            \"ColtrlDesc\": \"Америк ачааны автомашин\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL1\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BT04\",\n"
      + "            \"ColtrlDesc\": \"Герман ачааны автомашин\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL1\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BT05\",\n"
      + "            \"ColtrlDesc\": \"Орос  ачааны автомашин\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL1\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BT06\",\n"
      + "            \"ColtrlDesc\": \"Хятад  ачааны автомашин\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL1\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BT07\",\n"
      + "            \"ColtrlDesc\": \"Бусад улсын ачааны машин\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL1\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BM01\",\n"
      + "            \"ColtrlDesc\": \"Мотоцикл мопед\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL2\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BM02\",\n"
      + "            \"ColtrlDesc\": \"Өргөгч машин механизм\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL2\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BM03\",\n"
      + "            \"ColtrlDesc\": \"Нийтийн тээврийн хэрэгсэл\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL2\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"BM04\",\n"
      + "            \"ColtrlDesc\": \"ХАА-н тээврийн хэрэгсэл\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": \"MVL2\",\n"
      + "            \"Class\": \"MVL\"\n"
      + "        },\n"
      + "        {\n"
      + "            \"ColtrlCode\": \"VEH\",\n"
      + "            \"ColtrlDesc\": \"СУУДЛЫН МАШИН\",\n"
      + "            \"ColtrlType\": \"V\",\n"
      + "            \"CCY\": \"MNT\",\n"
      + "            \"ColtrlGroup\": null,\n"
      + "            \"Class\": null\n"
      + "        }\n"
      + "    ]\n"
      + "}\n";

  @Test
  public void verify_collateral_code()
  {
    JSONObject responseJSON = new JSONObject(collateralCodeResponse);
    JSONArray response = responseJSON.getJSONArray("Response");

    List<String> codeList = CollateralNewCoreUtil.toCollateralCodeList(response);

    Assert.assertEquals(18, codeList.size());
  }
}
