package mn.erin.bpm.domain.ohs.xac.util;

import org.json.JSONObject;
import org.junit.Assert;
import org.junit.Test;

import mn.erin.domain.base.model.person.AddressInfo;
import mn.erin.domain.bpm.model.customer.Customer;

/**
 * @author Tamir
 */
public class CustomerUtilTest
{
  private static final String RESPONSE = "Response";

  private static final String custInfoByRegNum = "{\n"
      + "   \"Source\":\"CAMUNDA\",\n"
      + "   \"Function\":\"SearchXBCustomer\",\n"
      + "   \"RequestId\":\"20200716172109\",\n"
      + "   \"UserId\":\"3337\",\n"
      + "   \"RequestType\":\"A\",\n"
      + "   \"Status\":\"SUCCESS\",\n"
      + "   \"SecurityCode\":\"27B4C3444D3A24E3FDEA94E67712EF17\",\n"
      + "   \"Response\":{\n"
      + "      \"brn\":\"101\",\n"
      + "      \"custno\":\"01282655\",\n"
      + "      \"custtype\":\"I\",\n"
      + "      \"custname\":\"Бат Найрамдал Оюу ХХК\",\n"
      + "      \"regno\":\"УА93112928\",\n"
      + "      \"passportno\":null,\n"
      + "      \"custcategory\":\"CAT8\",\n"
      + "      \"firstname\":null,\n"
      + "      \"middlename\":null,\n"
      + "      \"lastname\":null,\n"
      + "      \"prefix\":null,\n"
      + "      \"country\":\"MO51\"\n"
      + "   }\n"
      + "}";

  private static final String custInfoWithIntegerPhone = "{\n"
      + "    \"Source\": \"CAMUNDA\",\n"
      + "    \"UserId\": \"CAMUNDA\",\n"
      + "    \"Branch\": \"\",\n"
      + "    \"Function\": \"GetCRCustomerInfo\",\n"
      + "    \"SecurityCode\": \"715C4E4315DB45566BDEAE1782B4D266\",\n"
      + "    \"RequestType\": \"A\",\n"
      + "    \"RequestId\": \"132\",\n"
      + "    \"Status\": \"SUCCESS\",\n"
      + "    \"Response\": {\n"
      + "        \"PRIVATE_CUSTOMER\": \"N\",\n"
      + "        \"CUSTNO\": \"00356395\",\n"
      + "        \"CTYPE\": \"I\",\n"
      + "        \"NAME\": \"Дашдэндэв ГАНТОГОО\",\n"
      + "        \"ADDRLN1\": \"ADDRESS_1_00288288\",\n"
      + "        \"ADDRLN3\": \"ADDRESS_3_00288288\",\n"
      + "        \"ADDRLN2\": \"ADDRESS_2_00288288\",\n"
      + "        \"ADDRLN4\": \"ADDRESS_4_00288288\",\n"
      + "        \"COUNTRY\": \"MN\",\n"
      + "        \"SNAME\": \"КЮ81030501\",\n"
      + "        \"NLTY\": \"MN\",\n"
      + "        \"LBRN\": 101,\n"
      + "        \"CCATEG\": \"CAT10\",\n"
      + "        \"FULLNAME\": \"Дашдэндэв ГАНТОГОО\",\n"
      + "        \"CIFCREATIONDT\": \"2010-11-08\",\n"
      + "        \"ISELCMCUST\": \"Y\",\n"
      + "        \"AR_AP_TRACKING\": \"N\",\n"
      + "        \"EXPCNTRY\": \"MN\",\n"
      + "        \"UIDNAME\": \"Reg ID\",\n"
      + "        \"UIDVAL\": \"КЮ81030501\",\n"
      + "        \"FROZEN\": \"N\",\n"
      + "        \"DEAD\": \"N\",\n"
      + "        \"WHRUNKN\": \"N\",\n"
      + "        \"MAILRSREQD\": \"N\",\n"
      + "        \"EXPCAT\": \"BKB\",\n"
      + "        \"CUSTCLASSFN\": \"MO51\",\n"
      + "        \"CIFSTAT\": \"NORM\",\n"
      + "        \"CIFSTATSNC\": \"2010-11-08\",\n"
      + "        \"CLSPARTICIPANT\": \"N\",\n"
      + "        \"FXNETTCUST\": \"00356395\",\n"
      + "        \"XREF\": \"00356395\",\n"
      + "        \"CRMCUST\": \"N\",\n"
      + "        \"ISSUCUST\": \"N\",\n"
      + "        \"TRSRYCUST\": \"N\",\n"
      + "        \"RELPRICING\": \"Y\",\n"
      + "        \"MT920\": \"N\",\n"
      + "        \"FLGJOINT\": \"N\",\n"
      + "        \"CREATEACC\": \"N\",\n"
      + "        \"TRACK_LIMITS\": \"Y\",\n"
      + "        \"LIABID\": \"00356395\",\n"
      + "        \"LMCCY\": \"MNT\",\n"
      + "        \"FXCUSTCLRILIM\": 0,\n"
      + "        \"OVRLIM\": 99999999999,\n"
      + "        \"FX_CLEAN_RISK\": 0,\n"
      + "        \"SECCUSTCLRILIM\": 0,\n"
      + "        \"SECCLRILIM\": 0,\n"
      + "        \"SECCUSTPSRILIM\": 0,\n"
      + "        \"SECPSRILIM\": 0,\n"
      + "        \"FLGUTLTYPRVDR\": \"N\",\n"
      + "        \"AMLREQD\": \"Y\",\n"
      + "        \"AMLCUSTGRP\": \"00356395\",\n"
      + "        \"CHKDIGITVALREQD\": \"N\",\n"
      + "        \"FTACCASOF\": \"M\",\n"
      + "        \"CUSTUNADV\": \"N\",\n"
      + "        \"CONSTAXCERTRQD\": \"N\",\n"
      + "        \"INDTAXCERTRQD\": \"N\",\n"
      + "        \"CLSCCYALLWD\": \"D\",\n"
      + "        \"NETTREQD\": \"Y\",\n"
      + "        \"LIABUNADV\": \"N\",\n"
      + "        \"MAKER\": \"CAMUNDA\",\n"
      + "        \"MAKERSTAMP\": \"2019-07-07 14:43:02\",\n"
      + "        \"CHECKER\": \"CAMUNDA\",\n"
      + "        \"CHECKERSTAMP\": \"2019-07-07 14:43:09\",\n"
      + "        \"MODNO\": 15,\n"
      + "        \"TXNSTAT\": \"O\",\n"
      + "        \"AUTHSTAT\": \"A\",\n"
      + "        \"Custpersonal\": {\n"
      + "            \"FSTNAME\": \"ГАНТОГОО\",\n"
      + "            \"MIDNAME\": \"БОРЖИГОН\",\n"
      + "            \"LSTNAME\": \"Дашдэндэв\",\n"
      + "            \"DOB\": \"1981-03-05\",\n"
      + "            \"SEX\": \"F\",\n"
      + "            \"TELEPHNO\": 86035566,\n"
      + "            \"EMAILID\": \"erdene@gmail.com\",\n"
      + "            \"RESSTATUS\": \"R\",\n"
      + "            \"CUSTPREFIX1\": \"Адаацаг сум\",\n"
      + "            \"CUSTPREFIX2\": \"Баг 1\",\n"
      + "            \"MOBNUM\": 90502211,\n"
      + "            \"LANG\": \"MNG\",\n"
      + "            \"SBMTAGEPROOF\": \"N\",\n"
      + "            \"MINOR\": \"N\",\n"
      + "            \"KYCSTAT\": \"N\",\n"
      + "            \"SAME_CORR_ADDR\": \"N\",\n"
      + "            \"SAME_PERM_ADDR\": \"N\",\n"
      + "            \"USRESSTATUS\": \"N\",\n"
      + "            \"PAISSUED\": \"N\",\n"
      + "            \"VSTUSPREV\": \"N\",\n"
      + "            \"Custdomestic\": {\n"
      + "                \"CUSTNO\": \"00356395\",\n"
      + "                \"EDUSTAT\": \"G\",\n"
      + "                \"MARITALSTAT\": \"M\",\n"
      + "                \"SPNAME\": \"ЬPС***_00*56**5\",\n"
      + "                \"SPEMPSTATUS\": \"F\",\n"
      + "                \"DEPCHILD\": 0,\n"
      + "                \"DEPOTH\": 1,\n"
      + "                \"ACCOMODATE\": \"O\"\n"
      + "            }\n"
      + "        },\n"
      + "        \"Custcorp\": null,\n"
      + "        \"Doctype-Remarks\": {\n"
      + "            \"CUSTOMER_NO\": \"00356395\"\n"
      + "        },\n"
      + "        \"Custsegment\": {\n"
      + "            \"CUSTCCY\": \"MNT\",\n"
      + "            \"CUSTSEGCD\": \"I03\",\n"
      + "            \"CUSTSEGSTATUS\": \"U\",\n"
      + "            \"NETWORTH\": 32859.31,\n"
      + "            \"NETWORTHCCY\": \"MNT\"\n"
      + "        },\n"
      + "        \"Custmis\": {\n"
      + "            \"CUST\": \"00356395\",\n"
      + "            \"BRNCD\": 101,\n"
      + "            \"Customermis\": {\n"
      + "                \"MISCLS\": \"AO_CUSTOM\"\n"
      + "            },\n"
      + "            \"Compositemis\": {\n"
      + "                \"MISCLS\": \"IMPAIRED\"\n"
      + "            }\n"
      + "        },\n"
      + "        \"Custaccdet\": {\n"
      + "            \"CUSTNO\": \"00356395\",\n"
      + "            \"Relationship-Linkage\": {\n"
      + "                \"CUSTOMER\": \"00356395\",\n"
      + "                \"RELATIONSHIP\": \"PRIMARY\",\n"
      + "                \"INHERIT\": \"N\",\n"
      + "                \"DESCP\": \"Дашдэндэв ГАНТОГОО\"\n"
      + "            }\n"
      + "        },\n"
      + "        \"UDFDETAILS\": [\n"
      + "            {\n"
      + "                \"FLDNAM\": \"DIRECTOR_REG\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"AJLIIN_BAIR_HUUCHIN\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"AJLIIN_BAIR_SHINE\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"SURGUULID_SURDAG_ESEH\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"SURGULIYN_NER\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"TEMULEL_SURGALTAND_HAMRAGDSAN\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"HAMRAGDSAN_HUGATSAA\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"TEMULEL_MEDEELEL_AVSAN_SUVAG\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"TEMULEL_MEDEELEL_BUSAD_SUVAG\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"STUDENT\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"CUS_CATEGORY\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"GADAADIYN_IRGEN\",\n"
      + "                \"FLDVAL\": \"N\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"CONCENT_\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"TSALINGIYN_ZEELIYN_BAYGUULLAGA\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"SEGMENT\",\n"
      + "                \"FLDVAL\": \"I03\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"SERVICE\",\n"
      + "                \"FLDVAL\": 3\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"HARIUTSAH_AJILTAN\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"URGAH_NARAN\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"PARTICIPATED_BUSINESS_INCUBATION\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"HUGJLIIN_BERHSHEELTEI_ESEH\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"ACCOMODATION_TYPE\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"CORPORATE_EMPLOYEES\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"SE_ASSESSMENT\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"MEDEELEL_BUREN_AVSAN_ESEH\",\n"
      + "                \"FLDVAL\": \"Yes\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"PPCR\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"TSALINGIIN_BAIGUULLAGA\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"ONLINE_CIF_UUSGESEN_SOURCE\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"ONLINE_CIF_UUSGESEN_STATUS\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"MASTER_GEREE_OGNOO_CIF\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"RESISTENT\"\n"
      + "            }\n"
      + "        ]\n"
      + "    }\n"
      + "}";

  private static final String custInfo = "{\n"
      + "    \"Source\": \"CAMUNDA\",\n"
      + "    \"UserId\": \"CAMUNDA\",\n"
      + "    \"Branch\": \"\",\n"
      + "    \"Function\": \"GetCRCustomerInfo\",\n"
      + "    \"SecurityCode\": \"715C4E4315DB45566BDEAE1782B4D266\",\n"
      + "    \"RequestType\": \"A\",\n"
      + "    \"RequestId\": \"132\",\n"
      + "    \"Status\": \"SUCCESS\",\n"
      + "    \"Response\": {\n"
      + "        \"PRIVATE_CUSTOMER\": \"N\",\n"
      + "        \"CUSTNO\": \"00356395\",\n"
      + "        \"CTYPE\": \"I\",\n"
      + "        \"NAME\": \"Дашдэндэв ГАНТОГОО\",\n"
      + "        \"ADDRLN1\": \"ADDRESS_1_00288288\",\n"
      + "        \"ADDRLN3\": \"ADDRESS_3_00288288\",\n"
      + "        \"ADDRLN2\": \"ADDRESS_2_00288288\",\n"
      + "        \"ADDRLN4\": \"ADDRESS_4_00288288\",\n"
      + "        \"COUNTRY\": \"MN\",\n"
      + "        \"SNAME\": \"КЮ81030501\",\n"
      + "        \"NLTY\": \"MN\",\n"
      + "        \"LBRN\": 101,\n"
      + "        \"CCATEG\": \"CAT10\",\n"
      + "        \"FULLNAME\": \"Дашдэндэв ГАНТОГОО\",\n"
      + "        \"CIFCREATIONDT\": \"2010-11-08\",\n"
      + "        \"ISELCMCUST\": \"Y\",\n"
      + "        \"AR_AP_TRACKING\": \"N\",\n"
      + "        \"EXPCNTRY\": \"MN\",\n"
      + "        \"UIDNAME\": \"Reg ID\",\n"
      + "        \"UIDVAL\": \"КЮ81030501\",\n"
      + "        \"FROZEN\": \"N\",\n"
      + "        \"DEAD\": \"N\",\n"
      + "        \"WHRUNKN\": \"N\",\n"
      + "        \"MAILRSREQD\": \"N\",\n"
      + "        \"EXPCAT\": \"BKB\",\n"
      + "        \"CUSTCLASSFN\": \"MO51\",\n"
      + "        \"CIFSTAT\": \"NORM\",\n"
      + "        \"CIFSTATSNC\": \"2010-11-08\",\n"
      + "        \"CLSPARTICIPANT\": \"N\",\n"
      + "        \"FXNETTCUST\": \"00356395\",\n"
      + "        \"XREF\": \"00356395\",\n"
      + "        \"CRMCUST\": \"N\",\n"
      + "        \"ISSUCUST\": \"N\",\n"
      + "        \"TRSRYCUST\": \"N\",\n"
      + "        \"RELPRICING\": \"Y\",\n"
      + "        \"MT920\": \"N\",\n"
      + "        \"FLGJOINT\": \"N\",\n"
      + "        \"CREATEACC\": \"N\",\n"
      + "        \"TRACK_LIMITS\": \"Y\",\n"
      + "        \"LIABID\": \"00356395\",\n"
      + "        \"LMCCY\": \"MNT\",\n"
      + "        \"FXCUSTCLRILIM\": 0,\n"
      + "        \"OVRLIM\": 99999999999,\n"
      + "        \"FX_CLEAN_RISK\": 0,\n"
      + "        \"SECCUSTCLRILIM\": 0,\n"
      + "        \"SECCLRILIM\": 0,\n"
      + "        \"SECCUSTPSRILIM\": 0,\n"
      + "        \"SECPSRILIM\": 0,\n"
      + "        \"FLGUTLTYPRVDR\": \"N\",\n"
      + "        \"AMLREQD\": \"Y\",\n"
      + "        \"AMLCUSTGRP\": \"00356395\",\n"
      + "        \"CHKDIGITVALREQD\": \"N\",\n"
      + "        \"FTACCASOF\": \"M\",\n"
      + "        \"CUSTUNADV\": \"N\",\n"
      + "        \"CONSTAXCERTRQD\": \"N\",\n"
      + "        \"INDTAXCERTRQD\": \"N\",\n"
      + "        \"CLSCCYALLWD\": \"D\",\n"
      + "        \"NETTREQD\": \"Y\",\n"
      + "        \"LIABUNADV\": \"N\",\n"
      + "        \"MAKER\": \"CAMUNDA\",\n"
      + "        \"MAKERSTAMP\": \"2019-07-07 14:43:02\",\n"
      + "        \"CHECKER\": \"CAMUNDA\",\n"
      + "        \"CHECKERSTAMP\": \"2019-07-07 14:43:09\",\n"
      + "        \"MODNO\": 15,\n"
      + "        \"TXNSTAT\": \"O\",\n"
      + "        \"AUTHSTAT\": \"A\",\n"
      + "        \"Custpersonal\": {\n"
      + "            \"FSTNAME\": \"ГАНТОГОО\",\n"
      + "            \"MIDNAME\": \"БОРЖИГОН\",\n"
      + "            \"LSTNAME\": \"Дашдэндэв\",\n"
      + "            \"DOB\": \"1981-03-05\",\n"
      + "            \"SEX\": \"F\",\n"
      + "            \"TELEPHNO\": \"88970820 87987897 78987987\",\n"
      + "            \"EMAILID\": \"erdene@gmail.com\",\n"
      + "            \"RESSTATUS\": \"R\",\n"
      + "            \"CUSTPREFIX1\": \"Адаацаг сум\",\n"
      + "            \"CUSTPREFIX2\": \"Баг 1\",\n"
      + "            \"MOBNUM\": 90502211,\n"
      + "            \"LANG\": \"MNG\",\n"
      + "            \"SBMTAGEPROOF\": \"N\",\n"
      + "            \"MINOR\": \"N\",\n"
      + "            \"KYCSTAT\": \"N\",\n"
      + "            \"SAME_CORR_ADDR\": \"N\",\n"
      + "            \"SAME_PERM_ADDR\": \"N\",\n"
      + "            \"USRESSTATUS\": \"N\",\n"
      + "            \"PAISSUED\": \"N\",\n"
      + "            \"VSTUSPREV\": \"N\",\n"
      + "            \"Custdomestic\": {\n"
      + "                \"CUSTNO\": \"00356395\",\n"
      + "                \"EDUSTAT\": \"G\",\n"
      + "                \"MARITALSTAT\": \"M\",\n"
      + "                \"SPNAME\": \"ЬPС***_00*56**5\",\n"
      + "                \"SPEMPSTATUS\": \"F\",\n"
      + "                \"DEPCHILD\": 0,\n"
      + "                \"DEPOTH\": 1,\n"
      + "                \"ACCOMODATE\": \"O\"\n"
      + "            }\n"
      + "        },\n"
      + "        \"Custcorp\": null,\n"
      + "        \"Doctype-Remarks\": {\n"
      + "            \"CUSTOMER_NO\": \"00356395\"\n"
      + "        },\n"
      + "        \"Custsegment\": {\n"
      + "            \"CUSTCCY\": \"MNT\",\n"
      + "            \"CUSTSEGCD\": \"I03\",\n"
      + "            \"CUSTSEGSTATUS\": \"U\",\n"
      + "            \"NETWORTH\": 32859.31,\n"
      + "            \"NETWORTHCCY\": \"MNT\"\n"
      + "        },\n"
      + "        \"Custmis\": {\n"
      + "            \"CUST\": \"00356395\",\n"
      + "            \"BRNCD\": 101,\n"
      + "            \"Customermis\": {\n"
      + "                \"MISCLS\": \"AO_CUSTOM\"\n"
      + "            },\n"
      + "            \"Compositemis\": {\n"
      + "                \"MISCLS\": \"IMPAIRED\"\n"
      + "            }\n"
      + "        },\n"
      + "        \"Custaccdet\": {\n"
      + "            \"CUSTNO\": \"00356395\",\n"
      + "            \"Relationship-Linkage\": {\n"
      + "                \"CUSTOMER\": \"00356395\",\n"
      + "                \"RELATIONSHIP\": \"PRIMARY\",\n"
      + "                \"INHERIT\": \"N\",\n"
      + "                \"DESCP\": \"Дашдэндэв ГАНТОГОО\"\n"
      + "            }\n"
      + "        },\n"
      + "        \"UDFDETAILS\": [\n"
      + "            {\n"
      + "                \"FLDNAM\": \"DIRECTOR_REG\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"AJLIIN_BAIR_HUUCHIN\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"AJLIIN_BAIR_SHINE\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"SURGUULID_SURDAG_ESEH\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"SURGULIYN_NER\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"TEMULEL_SURGALTAND_HAMRAGDSAN\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"HAMRAGDSAN_HUGATSAA\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"TEMULEL_MEDEELEL_AVSAN_SUVAG\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"TEMULEL_MEDEELEL_BUSAD_SUVAG\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"STUDENT\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"CUS_CATEGORY\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"GADAADIYN_IRGEN\",\n"
      + "                \"FLDVAL\": \"N\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"CONCENT_\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"TSALINGIYN_ZEELIYN_BAYGUULLAGA\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"SEGMENT\",\n"
      + "                \"FLDVAL\": \"I03\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"SERVICE\",\n"
      + "                \"FLDVAL\": 3\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"HARIUTSAH_AJILTAN\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"URGAH_NARAN\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"PARTICIPATED_BUSINESS_INCUBATION\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"HUGJLIIN_BERHSHEELTEI_ESEH\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"ACCOMODATION_TYPE\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"CORPORATE_EMPLOYEES\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"SE_ASSESSMENT\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"MEDEELEL_BUREN_AVSAN_ESEH\",\n"
      + "                \"FLDVAL\": \"Yes\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"PPCR\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"TSALINGIIN_BAIGUULLAGA\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"ONLINE_CIF_UUSGESEN_SOURCE\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"ONLINE_CIF_UUSGESEN_STATUS\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"MASTER_GEREE_OGNOO_CIF\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"FLDNAM\": \"RESISTENT\"\n"
      + "            }\n"
      + "        ]\n"
      + "    }\n"
      + "}";

  @Test
  public void verifyStringTelephone()
  {
    JSONObject fullJson = new JSONObject(custInfo);

    JSONObject customerInfo = (JSONObject) fullJson.get("Response");
    Customer customer = CustomerUtil.toCustomerFullInfo(customerInfo, "СУ97124545", getAddressInfo());

    int size = customer.getContactInfoList().size();
    Assert.assertEquals(3, size);
  }

  @Test
  public void verifyIntegerTelephone()
  {
    JSONObject fullJson = new JSONObject(custInfoWithIntegerPhone);

    JSONObject customerInfo = (JSONObject) fullJson.get(RESPONSE);
    Customer customer = CustomerUtil.toCustomerFullInfo(customerInfo, "СУ97124545", getAddressInfo());

    int size = customer.getContactInfoList().size();
    Assert.assertEquals(1, size);
  }

  @Test
  public void verifyInfoByRegNumber()
  {
    JSONObject fullJson = new JSONObject(custInfoByRegNum);
    JSONObject customerInfoByRegNum = (JSONObject) fullJson.get(RESPONSE);

    Customer customer = CustomerUtil.toCustomer(customerInfoByRegNum);
    String firstName = customer.getPersonInfo().getFirstName();
    String lastName = customer.getPersonInfo().getLastName();

    String custNo = customer.getCustomerNumber();

    Assert.assertEquals("01282655", custNo);
    Assert.assertNotNull("Бат Найрамдал Оюу ХХК", firstName);
    Assert.assertNotNull("", lastName);
  }


  private AddressInfo getAddressInfo()
  {
    AddressInfo addressInfo = new AddressInfo();

    addressInfo.setStreet("a");
    addressInfo.setCity("b");
    addressInfo.setCountry("c");
    addressInfo.setQuarter("d");

    return addressInfo;
  }
}
