ALTER SESSION SET CURRENT_SCHEMA = ERIN;
-- DOCUMENT-INFO table 

SET DEFINE OFF;
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('01',null,'01. Өргөдөл','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('01.01','01','01. Өргөдөл, хүсэлт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('01.02','01','02. ХҮГ анкет и.үнэм','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('01.03','01','03. Зор зарцуулалт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('09.07','09','07. Барьцааны зураг','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('09.08','09','08. Ж/бус зөвшөөрөл','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('09.09','09','09. ТОС','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('21',null,'21. ХҮГ Баримт бичиг','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('21.01','21','01. Баримт бичиг','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('21.02','21','02. Т.Орлого','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('02.01','02','01Анкет и.үнэм хороо','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('21.03','21','03. Барьцаа','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('02.02','02','02 Т.гэр-гээ гэрлэлт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('02.03','02','03. ААН гэрчил дүрэм','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('02',null,'02. Эрх зүй','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('03',null,'03. Т.Орлого','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('03.05','03','05. НДД лавлагаа','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('04',null,'04. Лавлагаа','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('04.01','04','01. Лавлагаа','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('04.02','04','02. Бусад З.Г хуулга','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('05',null,'05. Бизнес','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('05.01','05','01. Зөвшөөрөл','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('05.02','05','02. Бизнес ү.ажил','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('05.03','05','03 ААН танилцуулга','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('05.04','05','04. Орж ирэх орлогын мэдээлэл','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('05.05','05','05. Тендерийн баримт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('05.06','05','06. Хөндлөнгийн дүгнэлт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('06',null,'06. Санхүү','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('06.01','06','01. Тогтмол орлого','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('06.02','06','02. Бизнес орлого','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('08',null,'08. Барьцаа','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('08.01','08','01. ҮХХ гэрчил лавла','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('08.02','08','02 Машин гэрчилгээ','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('08.03','08','03 Хөд.хөр гэрчилгээ','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('08.04','08','04 Үнэлгээний тайлан','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('08.05','08','05. Бусад','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('09',null,'09. Судалгаа','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('09.01','09','01 Хүүгийн тооцоолол','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('09.02','09','02 Судал.тэмдэглэл','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('09.03','09','03. Санал тооцоолол','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('09.04','09','04. Нэмэлт мэдээлэл','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('09.05','09','05. Бизнесийн зураг','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('09.06','09','06. Өрхийн зураг','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('10',null,'10 З.Шийдвэр','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('10.01','10','01. Зээлийн шийдвэр','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('10.02','10','02. ЗОЗ','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('10.03','10','03. Эрсдлийн дүгнэлт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('10.04','10','04. Хуулийн дүгнэлт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('10.05','10','05. БС эрсдэл дүгнэлт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('11',null,'11. З.Гэрээ','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('11.01','11','01. Үндсэн з.гэрээ','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('11.02','11','02. Бусад гэрээ','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('12',null,'12. Хяналт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('12.01','12','01 Зээл явцын тайлан','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('12.02','12','02 Жил хяналт тайлан','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('12.03','12','03. Анхаарал тайлан','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('12.04','12','04. Тусгай ү.тайлан','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('12.05','12','05. Бусад тайлан','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('13',null,'13 Төлүүлэлт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('13.01','13','01. Мэдэгдэх шаардах','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('13.02','13','02. Нэхэмжлэл','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('13.03','13','03. Шүүхийн шийдвэр','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('13.04','13','04 Шийдвэр гүйцэтгэл','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('13.05','13','05. Эвлэрлийн гэрээ','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('13.06','13','06. ӨБХ санал','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('13.07','13','07. ӨБХ гэрээ, гэрчилгээ','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('13.08','13','08. Худалдах гэрээ, шийдвэр','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('13.09','13','09. Хүлээлцсэн акт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('14',null,'14 Н.Өөрчлөл','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('14.01','14','01. Н.өөрчлөх баримт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('14.02','14','02 Н.өөрчлөх санал','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('14.03','14','03. Сан хаах санал','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('15',null,'15. Авлага','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('15.01','15','01 Батал-сан нэх-лэл','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('15.02','15','02. Нийлүүлэлт гэрээ ','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('15.03','15','03. Авлагын санал','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('15.04','15','04 Төлбөр зөвөөрөл','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('16',null,'16. Бөөний','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('16.01','16','01. Ү.а тайлан, төлөвлөгөө','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('16.02','16','02 Франчайзийн гэрээ','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('16.03','16','03. Бөөний зээлийн санал','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('16.04','16','04 Залруулсан тайлан','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('16.05','16','05. Гүйцэтгэл, ү.ажиллагааны  үнэлгээ','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('17',null,'17. Баталгаа','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('17.01','17','01. Баталгаа Хүсэлт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('17.02','17','02 Баталгаа мэдэгдэл','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('17.03','17','03. Хүсэлт баримт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('17.04','17','04 Мон, Eng баталгаа','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('17.05','17','05. Өөрч.цуц хүсэлт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('17.06','17','06. Цуцлах мэдэгдэл','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('17.07','17','07. Хүсэлт баримт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('17.08','17','08 Гүйлгээний баримт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('17.09','17','09. Баталгааны мэдээ','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('18',null,'18. Аккредитив','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('18.01','18','01 Аккредитив хүсэлт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('18.02','18','02. СВИФТ захиа','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('18.03','18','03 Аккредитив баримт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('18.04','18','04. Аккредитив өөрчлөх баримт','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('18.05','18','05. ХасБанкны захиа','IsRetail');
Insert into DOCUMENT_INFO (ID,DOCUMENT_PARENT_ID,NAME,TYPE) values ('18.06','18','06. Холбогдох материал','IsRetail');


-- PROCESS TYPE ---
SET DEFINE OFF;
INSERT INTO PROCESS_TYPE (PROCESS_TYPE_ID,DEFINITION_KEY,VERSION,NAME,PROCESS_DEFINITION_TYPE,PROCESS_TYPE_CATEGORY) values ('consumptionLoan','bpms_consumption_loan_case','1.0','Хэрэглээний зээл','CASE', 'LOAN');
Insert into PROCESS_TYPE (PROCESS_TYPE_ID,DEFINITION_KEY,VERSION,NAME,PROCESS_DEFINITION_TYPE,PROCESS_TYPE_CATEGORY) values ('microLoan','bpms_micro_loan_case','2.2','Бизнесийн зээл','CASE','LOAN');
Insert into PROCESS_TYPE (PROCESS_TYPE_ID,DEFINITION_KEY,VERSION,NAME,PROCESS_DEFINITION_TYPE,PROCESS_TYPE_CATEGORY) values ('mortgageLoan','bpms_mortgage_loan_case','2.3','Орон сууцны зээл','CASE','LOAN');

Insert into PROCESS_TYPE (PROCESS_TYPE_ID,DEFINITION_KEY,VERSION,NAME,PROCESS_DEFINITION_TYPE,PROCESS_TYPE_CATEGORY) values ('microLoanContract','bpms_loan_contract_case','4.7','Бизнесийн зээл','CASE','LOAN_CONTRACT');
Insert into PROCESS_TYPE (PROCESS_TYPE_ID,DEFINITION_KEY,VERSION,NAME,PROCESS_DEFINITION_TYPE,PROCESS_TYPE_CATEGORY) values ('consumptionLoanContract','bpms_loan_contract_case','4.7','Хэрэглээний зээл','CASE','LOAN_CONTRACT');
Insert into PROCESS_TYPE (PROCESS_TYPE_ID,DEFINITION_KEY,VERSION,NAME,PROCESS_DEFINITION_TYPE,PROCESS_TYPE_CATEGORY) values ('employeeLoanContract','bpms_loan_contract_case','4.7.1','Ажиллагсдын хэрэглээний зээл','CASE','LOAN_CONTRACT');
Insert into PROCESS_TYPE (PROCESS_TYPE_ID,DEFINITION_KEY,VERSION,NAME,PROCESS_DEFINITION_TYPE,PROCESS_TYPE_CATEGORY) values ('creditLineLoanContract','bpms_loan_contract_case','4.7.1','Шугамын зээл','CASE','LOAN_CONTRACT');
Insert into PROCESS_TYPE (PROCESS_TYPE_ID,DEFINITION_KEY,VERSION,NAME,PROCESS_DEFINITION_TYPE,PROCESS_TYPE_CATEGORY) values ('mortgageLoanContract','bpms_loan_contract_case','4.7.1','Моргейжийн зээл','CASE','LOAN_CONTRACT');
Insert into PROCESS_TYPE (PROCESS_TYPE_ID,DEFINITION_KEY,VERSION,NAME,PROCESS_DEFINITION_TYPE,PROCESS_TYPE_CATEGORY) values ('employeeMortgageLoanContract','bpms_loan_contract_case','4.7.1','Ажиллагсдын моргейжийн зээл','CASE','LOAN_CONTRACT');
Insert into PROCESS_TYPE (PROCESS_TYPE_ID,DEFINITION_KEY,VERSION,NAME,PROCESS_DEFINITION_TYPE,PROCESS_TYPE_CATEGORY) values ('directPrintingContract','bpms_loan_contract_case','4.7.1','Шууд хэвлэх гэрээ','CASE','LOAN_CONTRACT');
Insert into PROCESS_TYPE (PROCESS_TYPE_ID,DEFINITION_KEY,VERSION,NAME,PROCESS_DEFINITION_TYPE,PROCESS_TYPE_CATEGORY) values ('salaryOrganization','bpms_salary_organization_registration_case','4.10','Цалингийн байгууллага','CASE','ORGANIZATION');
Insert into PROCESS_TYPE (PROCESS_TYPE_ID,DEFINITION_KEY,VERSION,NAME,PROCESS_DEFINITION_TYPE,PROCESS_TYPE_CATEGORY) values ('leasingOrganization','bpms_leasing_organization_registration_case','4.10','Лизингийн байгууллага','CASE','ORGANIZATION');


---ERIN BPMS PRODUCT TABLE---
--------------------------------------------------------------
-- CONSUMER - Үндсэн төлбөр тэнцүү
--------------------------------------------------------------
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EB50', 'CONSUMER', 'Үндсэн төлбөр тэнцүү', 'EB50-365-Цалингийн зээл - Иргэн', 'Цалин', '1', 0 , 0);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EF50', 'CONSUMER', 'Үндсэн төлбөр тэнцүү', 'EF50-365-Ажиллагсадын хэрэглээний зээл', 'Цалин', '1', 0, 0);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EA50', 'CONSUMER', 'Үндсэн төлбөр тэнцүү', 'EA50-365-Өрхийн зээл - Иргэн', 'Өрх', '.70', 1 , 0);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EH53', 'CONSUMER', 'Үндсэн төлбөр тэнцүү', 'EH53-365-Хэрэглээний худалдан авалтын зээл - Иргэн', 'Худалдан авалт', '.80', 1 , 0);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EG50', 'CONSUMER', 'Үндсэн төлбөр тэнцүү', 'EG50-365- Сургалтын төлбөрийн зээл', 'Цалин', '1', 1 , 0);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EA52', 'CONSUMER', 'Үндсэн төлбөр тэнцүү', 'EA52-Эко хэрэглээний зээл -дулаалга', 'Өрх', '.70', 1 , 0);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EH90', 'CONSUMER', 'Үндсэн төлбөр тэнцүү', 'EH90-Автомашины зээл-Иргэн', 'Худалдан авалт', '.80', 1 , 1);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EH83', 'CONSUMER', 'Үндсэн төлбөр тэнцүү', 'EH83-Хаслизинг санхүү түрээс-Иргэн', 'Худалдан авалт', '.80', 1 , 1);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EH88', 'CONSUMER', 'Үндсэн төлбөр тэнцүү', 'EH88-Дугаартай автомашины зээл-Иргэн', 'Худалдан авалт', '.80', 1 , 1);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EH55', 'CONSUMER', 'Үндсэн төлбөр тэнцүү', 'EH55-365-Эко хэрэглээний зээл-Иргэн', 'Өрх', '.70', 1, 0);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EH56', 'CONSUMER', 'Үндсэн төлбөр тэнцүү', 'EH56-Эко хэрэглээний зээл /халаагуур/', 'Өрх', '.70', 1, 0);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EB71', 'CONSUMER', 'Үндсэн төлбөр тэнцүү', 'EB71-Онлайн цалингийн зээл', 'Цалин', '1', 0, 0);

--------------------------------------------------------------
-- CONSUMER - Нийт төлбөр тэнцүү
--------------------------------------------------------------
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EB51', 'CONSUMER', 'Нийт төлбөр тэнцүү', 'EB51-365-Цалингийн зээл -Иргэн –EMI', 'Цалин', '1', 0 , 0);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EA51', 'CONSUMER', 'Нийт төлбөр тэнцүү', 'EA51-365-Өрхийн зээл - Иргэн-EMI', 'Өрх', '0.70', 1 , 0);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EH54', 'CONSUMER', 'Нийт төлбөр тэнцүү', 'EH54-365-Хэрэглээний ХАЗ-EMI', 'Худалдан авалт', '.80', 1 , 0);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EH89', 'CONSUMER', 'Нийт төлбөр тэнцүү', 'EH89-EMI-Автомашины зээл-Иргэн', 'Худалдан авалт', '.80', 1 , 1);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EA53', 'CONSUMER', 'Нийт төлбөр тэнцүү', 'EA53-Эко хэрэглээний зээл-EMI /дулаалга/', 'Өрх', '.70', 1 ,0);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EH57', 'CONSUMER', 'Нийт төлбөр тэнцүү', 'EH57-Эко хэрэглээний зээл-EMI/халаагуур/', 'Өрх', '.70', 1, 0);

  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DA52', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DA52-365-Жижиг бизнесийн зээл-Иргэн', 'empty', '0.75', 1,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DA62', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DA62-365-Жижиг бизнесийн зээл-ААН', 'empty', '.75', 1,0, 'ААН');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DB50', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DB50-365-Бичил зээл-Иргэн', 'empty', '.80', 1 ,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DB51', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DB51-365-Бичил зээл-Иргэн Тусгай', 'empty', '.80', 1 ,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DB60', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DB60-365-Бичил зээл-ААН', 'empty', '.80', 1,0, 'ААН');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DA53', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DA53-365-Жижиг бизнесийн зээл Төсөл-Иргэн', 'empty', '.75', 1,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DA63', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DA63-365-Жижиг бизнесийн зээл Төсөл-ААН', 'empty', '.75', 1,0, 'ААН');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DA50', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DA50-365-ЖДҮСан төсөл-Иргэн', 'empty', '.75', 1,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD54', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DD54-365-Эко бизнесийн зээл-Иргэн', 'empty', '.70', 1,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DA65', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DA65-БОАЖЯ хамтарсан Жижиг биз.зээл-ААН', 'empty', '.75', 1 ,0, 'ААН');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD65', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DD65-365-Эко бизнесийн зээл-Эмэгтэй БЭ-ААН', 'empty', '.75', 1,0, 'ААН' );
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DJ85', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DJ85-365-Дугаартай автомашины зээл-ААН', 'empty', '1', 1,0 , 'ААН');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DB63', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DB63-ЖДҮХС-МБИҮНХ бичил биз.зээл-ААН', 'empty', '.80', 1,0 , 'ААН');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD64', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DD64-365-Эко бизнесийн зээл-ААН', 'empty', '.75', 1,0, 'ААН'  );
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD55', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DD55-365-Эко бизнесийн зээл-Эмэгтэй БЭ-Иргэн', 'empty', '.75', 1 ,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DA66', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DA66-ЖДҮХС-МБИҮНХ жижиг биз.зээл-ААН', 'empty', '.75', 1 ,0, 'ААН' );
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DB62', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DB62-БОАЖЯамтай хамтарсан Бичил бизнесийн зээл', 'empty', '.80', 1,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('EH53', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'EH53-365-Хэрэглээний худалдан авалтын зээл-Иргэн', 'empty', '1', 1 ,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('EG50', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'EG50-365- Сургалтын төлбөрийн зээл', 'empty', '1', 1 ,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('EA52', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'EA52-Эко хэрэглээний зээл-дулаалга', 'empty', '1', 1,0, 'Иргэн' );
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('EH90', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'EH90-Автомашины зээл-Иргэн', 'empty', '1', 1 ,1, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('EH83', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'EH83-Хаслизинг санхүү түрээс-Иргэн', 'empty', '1', 1,1, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('EH88', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'EH88-Дугаартай автомашины зээл-Иргэн', 'empty', '1', 1 ,1, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DJ83', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DJ83-Хаслизинг санхүү түрээс-ААН', 'empty', '1', 1 ,1, 'ААН' );
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('EH55', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'EH55-365-Эко хэрэглээний зээл-Иргэн', 'empty', '1', 1 ,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('EH56', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'EH56-Эко хэрэглээний зээл /халаагуур/', 'empty', '1', 1 ,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DB52', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DB52-Хөнгөлөлттэй бичил зээл', 'empty', '0.8', 1,0,'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD53', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DD53-365-Бизнесийн зээл Төсөл-Иргэн', 'empty', '0.8', 1,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD69', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DD69-Репо бизнес зээл /дахин санхүүжилт/', 'empty', '0.7', 1,0, 'ААН');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD70', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DD70-Репо бизнесийн зээл', 'empty', '0.7', 1,0, 'ААН');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD71', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DD71-Репо бизнесийн зээл-Иргэн /дахин санхүүжилт/', 'empty', '0.7', 1,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD72', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DD72-Репо бизнесийн зээл-Иргэн /шинэ/', 'empty', '0.7', 1,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DJ88', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DJ88-Автомашины зээл-ААН', 'empty', '1', 1, 0, 'ААН');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD81', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DD81-Ажлын байр дэмжих зээл-Иргэн /Дахин санхүүжилт/  ', 'empty', '0.8', 1,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD82', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DD82-Ажлын байр дэмжих зээл-Иргэн /Шинэ/', 'empty', '0.8', 1,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD73', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DD73-Ажлын байр дэмжих зээл-ААН /Дахин санхүүжилт/', 'empty', '0.7', 1,0, 'ААН');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD74', 'SMALL_MICRO', 'Үндсэн төлбөр тэнцүү', 'DD74-Ажлын байр дэмжих зээл-ААН /Шинэ/', 'empty', '0.7', 1,0, 'ААН');

  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD77', 'SMALL_MICRO', 'Нийт төлбөр тэнцүү', 'DD77-Ажлын байр дэмжих зээл-ААН-EMI/Дахин санхүүжилт/', 'empty', '0.7', 1,0, 'ААН' );
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD78', 'SMALL_MICRO', 'Нийт төлбөр тэнцүү', 'DD78-Ажлын байр дэмжих зээл-ААН-EMI/Шинэ/', 'empty', '0.7', 1, 0, 'ААН'  );
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD79', 'SMALL_MICRO', 'Нийт төлбөр тэнцүү', 'DD79-Ажлын байр дэмжих зээл-Иргэн-EMI-Ши', 'empty', '0.8', 1,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DD80', 'SMALL_MICRO', 'Нийт төлбөр тэнцүү', 'DD80-Ажлын байр дэмжих зээл-ИргэнEMI-Дах', 'empty', '0.8', 1,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('EH89', 'SMALL_MICRO', 'Нийт төлбөр тэнцүү', 'EH89-EMI-Автомашины зээл-Иргэн', 'empty', '1', 1,1, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('DJ87', 'SMALL_MICRO', 'Нийт төлбөр тэнцүү', 'DJ87-EMI-Автомашины зээл-ААН', 'empty', '1', 1, 1 , 'ААН');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('EA53', 'SMALL_MICRO', 'Нийт төлбөр тэнцүү', 'EA53-Эко хэрэглээний зээл-EMI /дулаалга/', 'empty', '1', 1,0, 'Иргэн');
  INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE, BORROWER_TYPE) VALUES('EH57', 'SMALL_MICRO', 'Нийт төлбөр тэнцүү', 'EH57-Эко хэрэглээний зээл-EMI/халаагуур/', 'empty', '1', 1,0, 'Иргэн');



--- MORTGAGE LOAN PRODUCTS ---
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('ED15', 'MORTGAGE', 'ЗГ(6% орон сууцны зээл)', 'ED15-EMI-Орон сууцны зээл ЗГ хөтөлбөр', 'empty', '0.7', 1, 1 );
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('ED16', 'MORTGAGE', 'ЗГ(6% орон сууцны зээл)', 'ED16-EMI-Шилжүүлсэн орон сууцны зээл ЗГ', 'empty', '0.7', 1, 1);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('ED17', 'MORTGAGE', 'Бусад(Бусад орон сууцны зээл)', 'ED17-АОСХА зээл ЗГ хөтөлбөр-МБ', 'empty', '0.7', 1, 1 );
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('ED18', 'MORTGAGE', 'Бусад(Бусад орон сууцны зээл)', 'ED18-АОСХА зээл ЗГ хөтөлбөр-Банк', 'empty', '0.7', 1, 1);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('ED24', 'MORTGAGE', 'Бусад(Бусад орон сууцны зээл)', 'ED24-Хашаа, АОС худалдан авах зээл /хувьсах хүүтэй/', 'empty', '0.7', 1, 1);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('ED28', 'MORTGAGE', 'Бусад(Бусад орон сууцны зээл)', 'ED28-Орон сууцны зээл ЗГ хөтөлбөр /Банк/', 'empty', '0.7', 1, 1);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('ED34', 'MORTGAGE', 'Бусад(Бусад орон сууцны зээл)', 'ED34-Хашаа, АОС барих зээл /хувьсах хүүтэй/', 'empty', '0.7', 1, 1);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('ED36', 'MORTGAGE', 'Бусад(Бусад орон сууцны зээл)', 'ED36-Эко амины орон сууц барих зээл', 'empty', '0.7', 1, 1);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('ED52', 'MORTGAGE', 'Бусад(Бусад орон сууцны зээл)', 'ED52-Нийтийн ОС худалдан авах зээл /хувьсах хүүтэй/', 'empty', '0.75', 1, 1);
INSERT INTO ERIN_BPMS_PRODUCT(PRODUCT_ID, APPLICATION_CATEGORY, CATEGORY_DESCRIPTION, PRODUCT_DESCRIPTION, TYPE, LOAN_TO_VALUE_RATIO, HAS_COLLATERAL, HAS_INSURANCE) VALUES('EF21', 'MORTGAGE', 'Бусад(Бусад орон сууцны зээл)', 'EF21-Ажиллагсадын ОС-ны зээл /Тогтмол хүүтэй/', 'empty', '0.85', 1, 1);


---ERIN BPMS  COLLATERAL PRODUCT TABLE---

-- Collateral products -Үл хөдлөх хөрөнгө

INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AB01', '1.Үл хөдлөх хөрөнгө', '1.Барилга', '1. Үйлдвэрийн барилга', 'Үйлдвэрийн барилга');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AB02', '1.Үл хөдлөх хөрөнгө', '1.Барилга', '2. Оффис, үйлчилгээний барилга', 'Үйлчилгээ оффисийн барилга');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AB03', '1.Үл хөдлөх хөрөнгө', '1.Барилга', '3. Шатахуун түгээх станц', 'Шатахуун түгээх станц');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AB04', '1.Үл хөдлөх хөрөнгө', '1.Барилга', '4. Нийтийн орон сууц', 'Нийтийн орон сууц');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AB05', '1.Үл хөдлөх хөрөнгө', '1.Барилга', '5. Амины сууц', 'Амины орон сууц');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AB06', '1.Үл хөдлөх хөрөнгө', '1.Барилга', '6. Дуусаагүй барилга ', 'Амины болон нийтийн орон сууцны дуусаагүй барилга');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AB07', '1.Үл хөдлөх хөрөнгө', '1.Барилга', '6. Дуусаагүй барилга ', 'Үйлчилгээний дуусаагүй барилга');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AB08', '1.Үл хөдлөх хөрөнгө', '1.Барилга', '6. Дуусаагүй барилга ', 'Үйлдвэрийн дуусаагүй барилга');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AB09', '1.Үл хөдлөх хөрөнгө', '1.Барилга', '7. Гараж', 'Гараж');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AB10', '1.Үл хөдлөх хөрөнгө', '1.Барилга', '8. Зоорь, агуулах', 'Зоорь');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AB11', '1.Үл хөдлөх хөрөнгө', '1.Барилга', '8. Зоорь, агуулах', 'Агуулах');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BO02', '1.Үл хөдлөх хөрөнгө', '1.Барилга', '8. Зоорь, агуулах', 'Павилион');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BK01', '1.Үл хөдлөх хөрөнгө', '1.Барилга', '8. Зоорь, агуулах', 'Чингэлэг   5-20тонн');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BK02', '1.Үл хөдлөх хөрөнгө', '1.Барилга', '8. Зоорь, агуулах', 'Чингэлэг     30-40 тн');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AS01', '1.Үл хөдлөх хөрөнгө', '2.Байгууламж', '9. Цахилгаан эрчим хүчний байгууламж', 'Цахилгаан эрчим хүчний байгууламж');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AS02', '1.Үл хөдлөх хөрөнгө', '2.Байгууламж', '10. Хөдөө аж ахуйн байгууламж', 'Хөдөө аж ахуйн байгууламж');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AB12', '1.Үл хөдлөх хөрөнгө', '3.Хашаа байшин (газрын хамт)', '11. Хувийн сууц', 'Хувийн сууц');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AS03', '1.Үл хөдлөх хөрөнгө', '3.Хашаа байшин (газрын хамт)', '11. Хувийн сууц', 'Хашаа байшин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AL01', '1.Үл хөдлөх хөрөнгө', '4.Газар', '12. Газар өмчлөх эрх', 'Өмчлөлийн газар');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AL02', '1.Үл хөдлөх хөрөнгө', '4.Газар', '13. Газар эзэмших эрх (Уул уурхай, газар тариалан, барилга барих зориулалттайгаас бусад)', 'Иргэний эзэмшлийн газар');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AL03', '1.Үл хөдлөх хөрөнгө', '4.Газар', '13. Газар эзэмших эрх (Уул уурхай, газар тариалан, барилга барих зориулалттайгаас бусад)', 'Хуулийн этгээдийн эзэмшлийн газар');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AL04', '1.Үл хөдлөх хөрөнгө', '4.Газар', '13. Газар эзэмших эрх', 'Уул уурхайн зориулалтаар ашиглах эрхтэй газар');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('AL05', '1.Үл хөдлөх хөрөнгө', '4.Газар', '13. Газар эзэмших эрх', 'Тариалангийн зориулалтаар эзэмших эрхтэй газар');

-- Collateral products -Хөдлөх хөрөнгө

INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BC01', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '14. Суудлын автомашин', 'Япон суудлын автомашин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BC02', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '14. Суудлын автомашин', 'Солонгос суудлын автомашин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BC03', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '14. Суудлын автомашин', 'Америк суудлын автомашин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BC04', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '14. Суудлын автомашин', 'Герман суудлын автомашин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BC05', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '14. Суудлын автомашин', 'Орос  суудлын автомашин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BC06', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '14. Суудлын автомашин', 'Бусад улсын суудлын автомашин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BT01', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '15. Ачааны автомашин', 'Япон ачааны автомашин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BT02', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '15. Ачааны автомашин', 'Солонгос ачааны автомашин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BT03', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '15. Ачааны автомашин', 'Америк ачааны автомашин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BT04', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '15. Ачааны автомашин', 'Герман ачааны автомашин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BT05', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '15. Ачааны автомашин', 'Орос ачааны автомашин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BT06', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '15. Ачааны автомашин', 'Хятад  ачааны автомашин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BT07', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '15. Ачааны автомашин', 'Бусад улсын ачааны автомашин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BM01', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '16. Мотоцикл, мопед', 'Мотоцикл, мопед');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BM02', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '17. Өргөгч машин, механизм', 'Өргөгч машин механизм');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BM03', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '18. Нийтийн тээврийн хэрэгсэл', 'Нийтийн тээврийн хэрэгсэл');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BM04', '2.Хөдлөх хөрөнгө', '5.Тээврийн хэрэгсэл', '19. Хөдөө аж ахуйн тээврийн хэрэгсэл', 'Хөдөө аж ахуйн тээврийн хэрэгсэл');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BI01', '2.Хөдлөх хөрөнгө', '6.Тоног төхөөрөмж', '20. Үйлдвэрлэлийн тоног төхөөрөмж', 'Үйлдвэрлэлийн тоног төхөөрөмж');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BI02', '2.Хөдлөх хөрөнгө', '6.Тоног төхөөрөмж', '21. Үйлчилгээний тоног төхөөрөмж', 'Үйлчилгээний тоног төхөөрөмж');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BI03', '2.Хөдлөх хөрөнгө', '6.Тоног төхөөрөмж', '21. Үйлчилгээний тоног төхөөрөмж', 'Эмнэлэгийн тоног төхөөрөмж');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BI04', '2.Хөдлөх хөрөнгө', '6.Тоног төхөөрөмж', '22. Хөдөө аж ахуйн тоног төхөөрөмж', 'Хөдөө аж ахуйн тоног төхөөрөмж');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BI05', '2.Хөдлөх хөрөнгө', '6.Тоног төхөөрөмж', '23. Бусад тоног төхөөрөмж', 'Албан тасалгааны тоног төхөөрөмж');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BI06', '2.Хөдлөх хөрөнгө', '6.Тоног төхөөрөмж', '23. Бусад тоног төхөөрөмж', 'Судалгаа шинжилгээний тоног төхөөрөмж');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BI07', '2.Хөдлөх хөрөнгө', '6.Тоног төхөөрөмж', '23. Бусад тоног төхөөрөмж', 'Сервер хамгаалалтын тоног төхөөрөмж');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BM05', '2.Хөдлөх хөрөнгө', '7.Мөнгө', '24. Хугацаатай/Хугацаагүй хадгаламж', 'Тээврийн хэрэгслийн урьдчилгаа');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CC02', '2.Хөдлөх хөрөнгө', '7.Мөнгө', '24. Хугацаатай/Хугацаагүй хадгаламж', 'Хадгаламжийн хүүгийн орлого');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CC03', '2.Хөдлөх хөрөнгө', '7.Мөнгө', '23. Хугацаатай/Хугацаагүй хадгаламж', 'Харилцах дансны хүүгийн орлого');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CL01', '2.Хөдлөх хөрөнгө', '7.Мөнгө', '23. Хугацаатай/Хугацаагүй хадгаламж', 'Хадгаламж');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CL02', '2.Хөдлөх хөрөнгө', '7.Мөнгө', '23. Хугацаатай/Хугацаагүй хадгаламж', 'Харилцах дансан дахь мөнгө');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CA01', '2.Хөдлөх хөрөнгө', '8.Мал', '25. Даатгагдсан мал', 'Даатгалтай бог мал');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CA03', '2.Хөдлөх хөрөнгө', '8.Мал', '25. Даатгагдсан мал', 'Даатгалтай бод мал');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CA02', '2.Хөдлөх хөрөнгө', '8.Мал', '26. Даатгагдаагүй мал', 'Даатгалгүй бог мал');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CA04', '2.Хөдлөх хөрөнгө', '8.Мал', '26. Даатгагдаагүй мал', 'Даатгалгүй бод мал');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CM01', '2.Хөдлөх хөрөнгө', '9.Бараа материал', '27. Бараа материал', 'Түүхий эд хагас боловсруулсан бүтээгдэхүүн');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CP01', '2.Хөдлөх хөрөнгө', '9.Бараа материал', '27. Бараа материал', 'Хүнсний бүтээгдэхүүн');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CP02', '2.Хөдлөх хөрөнгө', '9.Бараа материал', '27. Бараа материал', 'Бараа бэлэн бүтээгдэхүүн');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CP03', '2.Хөдлөх хөрөнгө', '9.Бараа материал', '27. Бараа материал', 'Гоо сайхны бүтээгдэхүүн ');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CP07', '2.Хөдлөх хөрөнгө', '9.Бараа материал', '27. Бараа материал', 'Барилгын материал');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CP05', '2.Хөдлөх хөрөнгө', '9.Бараа материал', '27. Бараа материал', 'Борлуулж буй тоног төхөөрөмж');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CP04', '2.Хөдлөх хөрөнгө', '9.Бараа материал', '27. Бараа материал', 'Эмийн болон химийн бүтээгдэхүүн');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CR01', '2.Хөдлөх хөрөнгө', '10.Авлага', '28. Авлага', 'Дансаарх авлага');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CC12', '2.Хөдлөх хөрөнгө', '10.Авлага', '28. Авлага', 'Батлан даалтын сан');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CC11', '2.Хөдлөх хөрөнгө', '10.Авлага', '29. Вексель', 'Вексел');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('DLIC', '2.Хөдлөх хөрөнгө', '10.Авлага', '29. Вексель', 'Үйл ажиллагаа явуулах зөвшөөрлөөс бусад лиценз');

-- Collateral products -Unsecured

INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CC01', 'Unsecured', 'Unsecured', '30. Цалингийн (Бизнесийн) орлого', 'Ногдол ашгийн орлого');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CC04', 'Unsecured', 'Unsecured', '30. Цалингийн (Бизнесийн) орлого', 'Тогтмол цалингийн орлого');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CC05', 'Unsecured', 'Unsecured', '30. Цалингийн (Бизнесийн) орлого', 'Ф-ийн гэрээтэй ХЗХ -ы гишүүдээс хувь нийлүүлсэн хөрөнгө');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CC06', 'Unsecured', 'Unsecured', '30. Цалингийн (Бизнесийн) орлого', 'Ф-ийн гэрээгүй ХЗХ -ы гишүүдээс хувь нийлүүлсэн хөрөнгө');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CC07', 'Unsecured', 'Unsecured', '30. Цалингийн (Бизнесийн) орлого', 'ББСБ-ын дүрмийн сан');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CC08', 'Unsecured', 'Unsecured', '30. Цалингийн (Бизнесийн) орлого', 'Тогтмол цалингийн орлого /Овердрафт/');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CC09', 'Unsecured', 'Unsecured', '30. Цалингийн (Бизнесийн) орлого', 'Хувьцаа');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CC10', 'Unsecured', 'Unsecured', '30. Цалингийн (Бизнесийн) орлого', 'Гэрээний орлого');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CC13', 'Unsecured', 'Unsecured', '30. Цалингийн (Бизнесийн) орлого', 'БИЗНЕСИЙН ОРЛОГО');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BO01', 'Unsecured', 'Unsecured', '31.Бусад', 'Хөгжмийн зэмсэг');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BC07', 'Unsecured', 'Unsecured', '31.Бусад', 'Унадаг дугуй');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BE01', 'Unsecured', 'Unsecured', '31.Бусад', 'Хөргөгч');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BE02', 'Unsecured', 'Unsecured', '31.Бусад', 'Угаалгын машин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BE03', 'Unsecured', 'Unsecured', '31.Бусад', 'Тоос сорогч');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BE04', 'Unsecured', 'Unsecured', '31.Бусад', 'Зурагт');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BE05', 'Unsecured', 'Unsecured', '31.Бусад', 'Хөлдөөгч');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BE06', 'Unsecured', 'Unsecured', '31.Бусад', 'Плитка');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BE07', 'Unsecured', 'Unsecured', '31.Бусад', 'Хөгжим');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BE08', 'Unsecured', 'Unsecured', '31.Бусад', 'Гэрийн театр');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BE09', 'Unsecured', 'Unsecured', '31.Бусад', 'Компьютер');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BE10', 'Unsecured', 'Unsecured', '31.Бусад', 'Видео камер');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BE11', 'Unsecured', 'Unsecured', '31.Бусад', 'Хувилагч машин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BE12', 'Unsecured', 'Unsecured', '31.Бусад', 'Принтер сканнер');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BE13', 'Unsecured', 'Unsecured', '31.Бусад', 'Шарах шүүгээ');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BE14', 'Unsecured', 'Unsecured', '31.Бусад', 'Зургийн аппарат');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BE15', 'Unsecured', 'Unsecured', '31.Бусад', 'Гар утас');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BE16', 'Unsecured', 'Unsecured', '31.Бусад', 'Халаагуур');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BF01', 'Unsecured', 'Unsecured', '31.Бусад', 'Албан тасалгааны тавилга хэрэгсэл');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BF02', 'Unsecured', 'Unsecured', '31.Бусад', 'Үйлдвэрлэлийн тавилга хэрэгсэл');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BF03', 'Unsecured', 'Unsecured', '31.Бусад', 'Үйлчилгээний тавилга хэрэгсэл');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BG01', 'Unsecured', 'Unsecured', '31.Бусад', '4 ханатай гэр');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BG02', 'Unsecured', 'Unsecured', '31.Бусад', '5 ханатай гэр');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BG03', 'Unsecured', 'Unsecured', '31.Бусад', '6 ханатай гэр');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BG04', 'Unsecured', 'Unsecured', '31.Бусад', '8 ханатай гэр');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BG05', 'Unsecured', 'Unsecured', '31.Бусад', '10 ханатай гэр');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BG06', 'Unsecured', 'Unsecured', '31.Бусад', 'Сийлбэртэй гэр');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BH01', 'Unsecured', 'Unsecured', '31.Бусад', 'Зочны өрөөний тавилга');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BH02', 'Unsecured', 'Unsecured', '31.Бусад', 'Унтлагын өрөөний тавилга');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BH03', 'Unsecured', 'Unsecured', '31.Бусад', 'Гал тогооны тавилга');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BH04', 'Unsecured', 'Unsecured', '31.Бусад', 'Хивс');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('BH05', 'Unsecured', 'Unsecured', '31.Бусад', 'Оёдолын машин');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CA05', 'Unsecured', 'Unsecured', '31.Бусад', 'Туслах аж ахуйн мал амьтад');
INSERT INTO ERIN_BPMS_COLLATERAL_PRODUCT(ID, TYPE, SUB_TYPE, MORE_INFORMATION, DESCRIPTION) VALUES ('CA06', 'Unsecured', 'Unsecured', '31.Бусад', 'Туслах аж ахуйн мал амьтад');
 


SET DEFINE OFF;
--- ERIN BPMS TASK FORM RELATION ---


/** calculate micro loan amount **/


INSERT INTO ERIN_BPMS_TASK_FORM_RELATION(TASK_DEFINITION_ID,FORM_VALUE,ENTITY)
    VALUES('user_task_new_core_create_vehicle_collateral', '{"amountOfCollateral": [{"updatedFieldId": "collateralAssessment","references": ["amountOfCollateral","amountOfCollateral","deductionRate","100"],"operations": ["-","*","/"],"operationType": "MATH","options": null}],"deductionRate": [{"updatedFieldId": "collateralAssessment","references": ["amountOfCollateral","amountOfCollateral","deductionRate","100"],"operations": ["-","*","/"],"operationType": "MATH","options": null}]}', 'JSON');

INSERT INTO ERIN_BPMS_TASK_FORM_RELATION(TASK_DEFINITION_ID,FORM_VALUE,ENTITY)
VALUES('user_task_new_core_create_other_collateral', '{"amountOfCollateral": [{"updatedFieldId": "collateralAssessment","references": ["amountOfCollateral","amountOfCollateral","deductionRate","100"],"operations": ["-","*","/"],"operationType": "MATH","options": null}],"deductionRate": [{"updatedFieldId": "collateralAssessment","references": ["amountOfCollateral","amountOfCollateral","deductionRate","100"],"operations": ["-","*","/"],"operationType": "MATH","options": null}]}', 'JSON');

INSERT INTO ERIN_BPMS_TASK_FORM_RELATION(TASK_DEFINITION_ID,FORM_VALUE,ENTITY)VALUES('user_task_new_core_create_immovable_collateral', '{"amountOfCollateral": [{"updatedFieldId": "collateralAssessment","references": ["amountOfCollateral","amountOfCollateral","deductionRate","100"],"operations": ["-","*","/"],"operationType": "MATH","options": null}],"deductionRate": [{"updatedFieldId": "collateralAssessment","references": ["amountOfCollateral","amountOfCollateral","deductionRate","100"],"operations": ["-","*","/"],"operationType": "MATH","options": null}]}', 'JSON');

INSERT INTO ERIN_BPMS_TASK_FORM_RELATION(TASK_DEFINITION_ID,FORM_VALUE,ENTITY)
VALUES('user_task_new_core_create_machinery_collateral', '{"amountOfCollateral": [{"updatedFieldId": "collateralAssessment","references": ["amountOfCollateral","amountOfCollateral","deductionRate","100"],"operations": ["-","*","/"],"operationType": "MATH","options": null}],"deductionRate": [{"updatedFieldId": "collateralAssessment","references": ["amountOfCollateral","amountOfCollateral","deductionRate","100"],"operations": ["-","*","/"],"operationType": "MATH","options": null}]}', 'JSON');


INSERT INTO ERIN_BPMS_TASK_FORM_RELATION(task_definition_id, form_value, entity) values('user_task_loan_transaction_permission_preparation', '{"preparationType":[{"updatedFieldId":"confirmedTotalAmount","operationType":"VALIDATION","operations":[],"references":["preparationType"],"options":{"preparationType":[{"id":"disbursementPermission","value":"Зээл олголтын зөвшөөрөл"}]}},{"updatedFieldId":"printCollateralList","operationType":"VALIDATION","operations":[],"references":["preparationType"],"options":{"preparationType":[{"id":"loanPermission","value":"Зээлийн эрх нээх зөвшөөрөл"}]}},{"updatedFieldId":"crossTrade","operationType":"VALIDATION","operations":[],"references":["preparationType"],"options":{"preparationType":[{"id":"loanPermission","value":"Зээлийн эрх нээх зөвшөөрөл"}]}},{"updatedFieldId":"closingAccountNumber","operationType":"VALIDATION","operations":[],"references":["preparationType"],"options":{"preparationType":[{"id":"loanPermission","value":"Зээлийн эрх нээх зөвшөөрөл"}]}},{"updatedFieldId":"loanRepaymentFee","operationType":"VALIDATION","operations":[],"references":["preparationType"],"options":{"preparationType":[{"id":"loanPermission","value":"Зээлийн эрх нээх зөвшөөрөл"}]}},{"updatedFieldId":"loanContractTotalAmount","operationType":"VALIDATION","operations":[],"references":["preparationType"],"options":{"preparationType":[{"id":"loanPermission","value":"Зээлийн эрх нээх зөвшөөрөл"}]}}]}','JSON');

INSERT INTO ERIN_BPMS_TASK_FORM_RELATION (TASK_DEFINITION_ID,FORM_VALUE, ENTITY) 
values ('user_task_leasing_organization_registration', '{
"feeOnlineBnpl":[{"updatedFieldId":"feeTerminalId","operationType":"REQUIRED_VALIDATION","operations":[],"references":["feeOnlineBnpl"],"options":{"feeOnlineBnpl":[{"id":"yes","value":"Тийм"}]}}],
"feeType":[{"updatedFieldId":"feeAmountPercent","operationType":"VALIDATION","operations":[],"references":["feeType"],"options":{"feeType":[{"id":"standard","value":"Стандарт"}]}},{"updatedFieldId":"feeAmountPercent","operationType":"TEXT","operations":[],"references":["feeType"],"options":{"standard":"2%"}}]}', 
'JSON');

INSERT INTO ERIN_BPMS_TASK_FORM_RELATION (TASK_DEFINITION_ID,FORM_VALUE, ENTITY) 
values ('user_task_salary_organization_registration', '{
"feeSalaryDays":[{"updatedFieldId":"feeSalaryDaysSecond","operationType":"VALIDATION","operations":[],"references":["feeSalaryDays"],"options":{"feeSalaryDays":[{"id":"oneTime","value":"1 удаа"}]}}],
"feeOrganizationRating":[{"updatedFieldId":"feeAmountPercent","operationType":"TEXT","operations":[],"references":["feeOrganizationRating"],"options":{"b":"2","c":"2.2","a":"1.8"}}],
"feeType":[{"updatedFieldId":"feeAmountPercent","operationType":"VALIDATION","operations":[],"references":["feeType"],"options":{"feeType":[{"id":"standard","value":"Стандарт"}]}}]}', 
'JSON');


----ERIN BPMS DEFAULT PARAMETER TABLE ----

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('LoanCalculation', 'Holidays', '2022', '2022-01-01; 2022-02-01; 2022-02-02; 2022-02-03; 2022-03-08; 2022-05-16; 2022-06-01; 2022-07-11; 2022-07-12; 2022-07-13; 2022-07-14; 2022-07-15; 2022-11-26; 2022-12-29', 'LIST');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('LoanCalculation', 'Holidays', '2023', '2023-01-01; 2023-01-22; 2023-01-23; 2023-01-24; 2023-03-08; 2023-05-05; 2023-06-01; 2023-07-11; 2023-07-12; 2023-07-13; 2023-07-14; 2023-07-15; 2023-11-14; 2023-11-26; 2023-12-29', 'LIST');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('LoanCalculation', 'Holidays', '2024', '2024-01-01; 2024-02-10; 2024-02-11; 2024-02-12; 2024-03-08; 2024-05-23; 2024-06-01; 2024-07-11; 2024-07-12; 2024-07-13; 2024-07-14; 2024-07-15; 2024-11-26; 2024-12-29', 'LIST');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('LoanCalculation', 'Holidays', '2025', '2025-01-01; 2025-01-29; 2025-01-30; 2025-01-31; 2025-03-08; 2025-05-12; 2025-06-01; 2025-07-11; 2025-07-12; 2025-07-13; 2025-07-14; 2025-07-15; 2025-11-26; 2025-12-29', 'LIST');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('LoanCalculation', 'Holidays', '2026', '2026-01-01; 2026-02-17; 2026-02-18; 2026-02-19; 2026-03-08; 2026-06-01; 2026-07-11; 2026-07-12; 2026-07-13; 2026-07-14; 2026-07-15; 2026-11-26; 2026-12-29', 'LIST');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('LoanCalculation', 'Holidays', '2027', '2027-01-01; 2027-02-06; 2027-02-07; 2027-02-08; 2027-03-08; 2027-06-01; 2027-07-11; 2027-07-12; 2027-07-13; 2027-07-14; 2027-07-15; 2027-11-26; 2027-12-29', 'LIST');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('LoanCalculation', 'Holidays', '2028', '2028-01-01; 2028-01-26; 2028-01-27; 2028-01-28; 2028-03-08; 2028-06-01; 2028-07-11; 2028-07-12; 2028-07-13; 2028-07-14; 2028-07-15; 2028-11-26; 2028-12-29', 'LIST');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('LoanCalculation', 'Holidays', '2029', '2029-01-01; 2029-02-13; 2029-02-14; 2029-02-15; 2029-03-08; 2029-06-01; 2029-07-11; 2029-07-12; 2029-07-13; 2029-07-14; 2029-07-15; 2029-11-26; 2029-12-29', 'LIST');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('ConsumptionLoan', 'SalaryCalculation', '2018', '{"1": {"minimumWage":  264000, "socialInsurancePremiums": 0.11},"2": {"minimumWage": 264000, "socialInsurancePremiums": 0.11},"3": {"minimumWage": 264000, "socialInsurancePremiums": 0.11},"4": {"minimumWage": 264000, "socialInsurancePremiums": 0.11},"5": {"minimumWage": 264000, "socialInsurancePremiums": 0.11},"6": {"minimumWage": 264000, "socialInsurancePremiums": 0.11},"7": {"minimumWage": 264000, "socialInsurancePremiums": 0.11},"8": {"minimumWage": 264000, "socialInsurancePremiums": 0.11},"9": {"minimumWage": 264000, "socialInsurancePremiums": 0.11},"10": {"minimumWage": 264000, "socialInsurancePremiums": 0.11},"11": {"minimumWage": 264000, "socialInsurancePremiums": 0.11},"12": {"minimumWage": 264000, "socialInsurancePremiums": 0.11}}', 'JSON');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('ConsumptionLoan', 'SalaryCalculation', '2019', '{"1": {"minimumWage":  368000, "socialInsurancePremiums": 0.115},"2": {"minimumWage": 368000, "socialInsurancePremiums": 0.115},"3": {"minimumWage": 368000, "socialInsurancePremiums": 0.115},"4": {"minimumWage": 368000, "socialInsurancePremiums": 0.115},"5": {"minimumWage": 368000, "socialInsurancePremiums": 0.115},"6": {"minimumWage": 368000, "socialInsurancePremiums": 0.115},"7": {"minimumWage": 368000, "socialInsurancePremiums": 0.115},"8": {"minimumWage": 368000, "socialInsurancePremiums": 0.115},"9": {"minimumWage": 368000, "socialInsurancePremiums": 0.115},"10": {"minimumWage": 368000, "socialInsurancePremiums": 0.115},"11": {"minimumWage": 368000, "socialInsurancePremiums": 0.115},"12": {"minimumWage": 368000, "socialInsurancePremiums": 0.115}}', 'JSON');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('ConsumptionLoan', 'SalaryCalculation', '2020', '{"1": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"2": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"3": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"4": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"5": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"6": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"7": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"8": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"9": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"10": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"11": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"12": {"minimumWage": 420000, "socialInsurancePremiums": 0.115}}', 'JSON');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('ConsumptionLoan', 'SalaryCalculation', '2021', '{"1": {"minimumWage": 420000, "socialInsurancePremiums": 0.125},"2": {"minimumWage": 420000, "socialInsurancePremiums": 0.125},"3": {"minimumWage": 420000, "socialInsurancePremiums": 0.125},"4": {"minimumWage": 420000, "socialInsurancePremiums": 0.125},"5": {"minimumWage": 420000, "socialInsurancePremiums": 0.125},"6": {"minimumWage": 420000, "socialInsurancePremiums": 0.125},"7": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"8": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"9": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"10": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"11": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"12": {"minimumWage": 420000, "socialInsurancePremiums": 0.115}}', 'JSON');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('ConsumptionLoan', 'SalaryCalculation', '2022', '{"1": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"2": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"3": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"4": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"5": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"6": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"7": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"8": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"9": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"10": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"11": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"12": {"minimumWage": 420000, "socialInsurancePremiums": 0.115}}', 'JSON');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('ConsumptionLoan', 'SalaryCalculation', '2023', '{"1": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"2": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"3": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"4": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"5": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"6": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"7": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"8": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"9": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"10": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"11": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"12": {"minimumWage": 420000, "socialInsurancePremiums": 0.115}}', 'JSON');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('ConsumptionLoan', 'SalaryCalculation', '2024', '{"1": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"2": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"3": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"4": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"5": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"6": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"7": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"8": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"9": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"10": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"11": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"12": {"minimumWage": 420000, "socialInsurancePremiums": 0.115}}', 'JSON');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('ConsumptionLoan', 'SalaryCalculation', '2025', '{"1": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"2": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"3": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"4": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"5": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"6": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"7": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"8": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"9": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"10": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"11": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"12": {"minimumWage": 420000, "socialInsurancePremiums": 0.115}}', 'JSON');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('ConsumptionLoan', 'SalaryCalculation', '2026', '{"1": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"2": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"3": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"4": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"5": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"6": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"7": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"8": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"9": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"10": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"11": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"12": {"minimumWage": 420000, "socialInsurancePremiums": 0.115}}', 'JSON');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('ConsumptionLoan', 'SalaryCalculation', '2027', '{"1": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"2": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"3": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"4": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"5": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"6": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"7": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"8": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"9": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"10": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"11": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"12": {"minimumWage": 420000, "socialInsurancePremiums": 0.115}}', 'JSON');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('ConsumptionLoan', 'SalaryCalculation', '2028', '{"1": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"2": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"3": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"4": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"5": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"6": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"7": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"8": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"9": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"10": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"11": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"12": {"minimumWage": 420000, "socialInsurancePremiums": 0.115}}', 'JSON');

INSERT INTO ERIN_BPMS_DEFAULT_PARAMETER(PROCESS_TYPE, ENTITY, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_DATA_TYPE) VALUES ('ConsumptionLoan', 'SalaryCalculation', '2029', '{"1": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"2": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"3": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"4": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"5": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"6": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"7": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"8": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"9": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"10": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"11": {"minimumWage": 420000, "socialInsurancePremiums": 0.115},"12": {"minimumWage": 420000, "socialInsurancePremiums": 0.115}}', 'JSON');

Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatDiscount','2017','{"6000000":"160000","12000000":"140000","18000000":"120000","24000000":"100000","30000000":"80000","36000000":"60000"}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatDiscount','2018','{"6000000":"160000","12000000":"140000","18000000":"120000","24000000":"100000","30000000":"80000","36000000":"60000"}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatDiscount','2019','{"6000000":"240000","12000000":"216000","18000000":"192000","24000000":"168000","30000000":"144000","36000000":"120000"}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatDiscount','2020','{"6000000":"240000","12000000":"216000","18000000":"192000","24000000":"168000","30000000":"144000","36000000":"120000"}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatDiscount','2021','{"6000000":"240000","12000000":"216000","18000000":"192000","24000000":"168000","30000000":"144000","36000000":"120000"}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatDiscount','2022','{"6000000":"240000","12000000":"216000","18000000":"192000","24000000":"168000","30000000":"144000","36000000":"120000"}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatDiscount','2023','{"6000000":"240000","12000000":"216000","18000000":"192000","24000000":"168000","30000000":"144000","36000000":"120000"}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatDiscount','2024','{"6000000":"240000","12000000":"216000","18000000":"192000","24000000":"168000","30000000":"144000","36000000":"120000"}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatDiscount','2025','{"6000000":"240000","12000000":"216000","18000000":"192000","24000000":"168000","30000000":"144000","36000000":"120000"}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatDiscount','2026','{"6000000":"240000","12000000":"216000","18000000":"192000","24000000":"168000","30000000":"144000","36000000":"120000"}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatDiscount','2027','{"6000000":"240000","12000000":"216000","18000000":"192000","24000000":"168000","30000000":"144000","36000000":"120000"}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatDiscount','2028','{"6000000":"240000","12000000":"216000","18000000":"192000","24000000":"168000","30000000":"144000","36000000":"120000"}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatDiscount','2029','{"6000000":"240000","12000000":"216000","18000000":"192000","24000000":"168000","30000000":"144000","36000000":"120000"}','JSON');

Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatTax','2017','10','String');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatTax','2018','10','String');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatTax','2019','10','String');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatTax','2020','10','String');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatTax','2021','10','String');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatTax','2022','10','String');

Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatTaxNew','2023','{"0":{"taxPercent":"10","maxIncome":"120000000","constantTax":"0"},"1":{"taxPercent":"10","taxPercentAdded":"15","maxIncome":"180000000","constantTax":"12000000"},"2":{"taxPercent":"10","taxPercentAdded":"20","maxIncome":"0","constantTax":"21000000"}}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatTaxNew','2024','{"0":{"taxPercent":"10","maxIncome":"120000000","constantTax":"0"},"1":{"taxPercent":"10","taxPercentAdded":"15","maxIncome":"180000000","constantTax":"12000000"},"2":{"taxPercent":"10","taxPercentAdded":"20","maxIncome":"0","constantTax":"21000000"}}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatTaxNew','2025','{"0":{"taxPercent":"10","maxIncome":"120000000","constantTax":"0"},"1":{"taxPercent":"10","taxPercentAdded":"15","maxIncome":"180000000","constantTax":"12000000"},"2":{"taxPercent":"10","taxPercentAdded":"20","maxIncome":"0","constantTax":"21000000"}}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatTaxNew','2026','{"0":{"taxPercent":"10","maxIncome":"120000000","constantTax":"0"},"1":{"taxPercent":"10","taxPercentAdded":"15","maxIncome":"180000000","constantTax":"12000000"},"2":{"taxPercent":"10","taxPercentAdded":"20","maxIncome":"0","constantTax":"21000000"}}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatTaxNew','2027','{"0":{"taxPercent":"10","maxIncome":"120000000","constantTax":"0"},"1":{"taxPercent":"10","taxPercentAdded":"15","maxIncome":"180000000","constantTax":"12000000"},"2":{"taxPercent":"10","taxPercentAdded":"20","maxIncome":"0","constantTax":"21000000"}}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatTaxNew','2028','{"0":{"taxPercent":"10","maxIncome":"120000000","constantTax":"0"},"1":{"taxPercent":"10","taxPercentAdded":"15","maxIncome":"180000000","constantTax":"12000000"},"2":{"taxPercent":"10","taxPercentAdded":"20","maxIncome":"0","constantTax":"21000000"}}','JSON');
Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','HhoatTaxNew','2029','{"0":{"taxPercent":"10","maxIncome":"120000000","constantTax":"0"},"1":{"taxPercent":"10","taxPercentAdded":"15","maxIncome":"180000000","constantTax":"12000000"},"2":{"taxPercent":"10","taxPercentAdded":"20","maxIncome":"0","constantTax":"21000000"}}','JSON');

Insert into ERIN_BPMS_DEFAULT_PARAMETER (PROCESS_TYPE,ENTITY,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_DATA_TYPE) values ('SalaryCalculation','MinSalaryForDiscount','minAmount','36000000','String');



--- BI PATH TABLE---

INSERT INTO BI_PATH (PROCESS_TYPE_ID, PRODUCT_CODE, FOLDER, PATH) VALUES ('consumptionLoanContract', 'EB50', 'Finacle Contracts', 'XBRCOLA');
INSERT INTO BI_PATH (PROCESS_TYPE_ID, PRODUCT_CODE, FOLDER, PATH) VALUES ('creditLineLoanContract', 'DL1500', 'Finacle Contracts', 'XBRCRLA');
INSERT INTO BI_PATH (PROCESS_TYPE_ID, PRODUCT_CODE, FOLDER, PATH) VALUES ('directPrintingContract', 'EE31', 'Finacle Contracts', 'XBZ_CONT');
INSERT INTO BI_PATH (PROCESS_TYPE_ID, PRODUCT_CODE, FOLDER, PATH) VALUES ('employeeLoanContract', 'EF50', 'Finacle Contracts', 'xbresl');
INSERT INTO BI_PATH (PROCESS_TYPE_ID, PRODUCT_CODE, FOLDER, PATH) VALUES ('employeeMortgageLoanContract', 'EF21', 'Finacle Contracts', 'XBREMLC');
INSERT INTO BI_PATH (PROCESS_TYPE_ID, PRODUCT_CODE, FOLDER, PATH) VALUES ('microLoanContract', 'DA52', 'Finacle Contracts','XBRCOLA');
INSERT INTO BI_PATH (PROCESS_TYPE_ID, PRODUCT_CODE, FOLDER, PATH) VALUES ('mortgageLoanContract', 'ED28', 'Finacle Contracts', 'XBRMLC');
INSERT INTO BI_PATH (PROCESS_TYPE_ID, PRODUCT_CODE, FOLDER, PATH) VALUES ('consumptionLoanContract', 'EB51', 'Finacle Contracts', 'XBRCOLA');
INSERT INTO BI_PATH (PROCESS_TYPE_ID, PRODUCT_CODE, FOLDER, PATH) VALUES ('creditLineLoanContract', 'AA140', 'Finacle Contracts', 'XBRCRLA');
INSERT INTO BI_PATH (PROCESS_TYPE_ID, PRODUCT_CODE, FOLDER, PATH) VALUES ('directPrintingContract', 'EE32', 'Finacle Contracts', 'XBZ_CONT');
INSERT INTO BI_PATH (PROCESS_TYPE_ID, PRODUCT_CODE, FOLDER, PATH) VALUES ('microLoanContract', 'DD64', 'Finacle Contracts', 'XBRCOLA');
INSERT INTO BI_PATH (PROCESS_TYPE_ID, PRODUCT_CODE, FOLDER, PATH) VALUES ('mortgageLoanContract', 'ED16', 'Finacle Contracts', 'XBRMLC');
