ALTER SESSION SET CURRENT_SCHEMA = ERIN;
INSERT INTO AIM_ROLE (ROLE_ID, TENANT_ID,NAME) values ('teller', 'xac','Теллер');
INSERT INTO AIM_ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) values ('teller','bpms.bpm.BranchBanking');
INSERT INTO AIM_ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) values ('teller','bpms.bpm.StartProcess');

INSERT INTO aim_membership (membership_id, user_id, group_id, role_id, tenant_id)
values('71574c89-7dec-4925-83fb-9dd5b98b6a6z', '2226', '108', 'teller', 'xac');


INSERT INTO PROCESS_TYPE (PROCESS_TYPE_ID,DEFINITION_KEY,VERSION,NAME,PROCESS_DEFINITION_TYPE,PROCESS_TYPE_CATEGORY) values ('branchBankingCustomer','branch_banking_customer_case','4.0','Харилцагч','CASE','BRANCHBANKING');
INSERT INTO PROCESS_TYPE (PROCESS_TYPE_ID,DEFINITION_KEY,VERSION,NAME,PROCESS_DEFINITION_TYPE,PROCESS_TYPE_CATEGORY) values ('branchBankingGuest','branch_banking_guest_case','4.0','Зочин','CASE','BRANCHBANKING');
Insert into PROCESS_TYPE (PROCESS_TYPE_ID,DEFINITION_KEY,VERSION,NAME,PROCESS_DEFINITION_TYPE,PROCESS_TYPE_CATEGORY) values ('branchBankingForeignCustomer','branch_banking_foreign_customer_case','4.0','Гадаад улсын иргэн','CASE','BRANCHBANKING');


----ERIN_BPMS_TASK_FORM_RELATION_TABLE-----

INSERT INTO ERIN_BPMS_TASK_FORM_RELATION (TASK_DEFINITION_ID,FORM_VALUE, ENTITY) values ('user_task_branch_banking_tax_pay', '{"searchType":[{"updatedFieldId":"taxNumber","operationType":"VALIDATION","operations":[],"references":["searchType"],"options":{"searchType":[{"id":"propertyNumber","value":"Хөрөнгийн дугаар"},{"id":"invoiceNumber","value":"Нэхэмжлэхийн дугаар"},{"id":"ttdOption","value":"ТТД"}]}},{"updatedFieldId":"taxNumber","references":["searchType"],"operations":[],"operationType":"TEXT","options":{"propertyNumber":null,"invoiceNumber":null,"ttdOption":null}}]}', 'JSON');

INSERT INTO ERIN_BPMS_TASK_FORM_RELATION(task_definition_id, form_value, entity)
values('user_task_branch_banking_tax_pay_child', '{"payFull":[{"updatedFieldId":"invoiceAmount","operationType":"VALIDATION_TEXT_REFERENCE","operations":[],"references":["payFull"],"options":{"payFull":"1"}}],"transactionType":[{"updatedFieldId":"accountNumber","operationType":"VALIDATION","operations":[],"references":["transactionType"],"options":{"transactionType":[{"id":"cash","value":"Бэлэн"}]}},{"updatedFieldId":"accountNumber","operationType":"REQUIRED_VALIDATION","operations":[],"references":["transactionType"],"options":{"transactionType":[{"id":"nonCash","value":"Бэлэн бус"}]}},{"updatedFieldId":"accountNumber","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":""}},{"updatedFieldId":"accountName","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":""}},{"updatedFieldId":"accountBalance","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":""}},{"updatedFieldId":"accountCurrency","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":""}},{"updatedFieldId":"deductionAmount","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":""}},{"updatedFieldId":"payCutAmount","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":""}}]}', 'JSON');

INSERT INTO ERIN_BPMS_TASK_FORM_RELATION(task_definition_id, form_value, entity)values('user_task_branch_banking_custom_pay_child', '{"transactionType":[{"updatedFieldId":"accountNumber","operationType":"VALIDATION","operations":[],"references":["transactionType"],"options":{"transactionType":[{"id":"cash","value":"Бэлэн"}]}},{"updatedFieldId":"accountNumber","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":""}},{"updatedFieldId":"accountName","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":""}},{"updatedFieldId":"accountBalance","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":""}},{"updatedFieldId":"accountCurrency","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":""}},{"updatedFieldId":"deductionAmount","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":""}},{"updatedFieldId":"payCutAmount","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":""}}]}', 'JSON');

INSERT INTO ERIN_BPMS_TASK_FORM_RELATION (TASK_DEFINITION_ID,FORM_VALUE, ENTITY) 
values ('user_task_branch_banking_customer_transaction_form', '{"transactionFormType":[{"updatedFieldId":"customerName","operationType":"VALIDATION","operations":[],"references":["transactionFormType"],"options":{"transactionFormType":[{"id":"expenseTransactionReceipt","value":"Зарлагын маягт"},{"id":"paymentForm","value":"Төлбөрийн маягт"},{"id":"customPayTransactionReceipt","value":"Гаалийн гүйлгээний маягт"},{"id":"memorialOrderTransaction","value":"Мемориалын ордер маягт "}]}},{"updatedFieldId":"registerId","operationType":"VALIDATION","operations":[],"references":["transactionFormType"],"options":{"transactionFormType":[{"id":"incomeTransactionReceipt","value":"Орлогын маягт"},{"id":"currencyExchangeReceipt","value":"Валют арилжааны маягт"},{"id":"expenseTransactionReceipt","value":"Зарлагын маягт"},{"id":"paymentForm","value":"Төлбөрийн маягт"},{"id":"customPayTransactionReceipt","value":"Гаалийн гүйлгээний маягт"},{"id":"memorialOrderTransaction","value":"Мемориалын ордер маягт"}]}},{"updatedFieldId":"customerName","references":["transactionFormType"],"operations":[],"operationType":"TEXT","options":{"expenseTransactionReceipt":"","paymentForm":"","customPayTransactionReceipt":"","memorialOrderTransaction":""}},{"updatedFieldId":"registerId","references":["transactionFormType"],"operations":[],"operationType":"TEXT","options":{"incomeTransactionReceipt":"","currencyExchangeReceipt":"","expenseTransactionReceipt":"","paymentForm":"","customPayTransactionReceipt":"","memorialOrderTransaction":""}}]}', 'JSON');

INSERT INTO ERIN_BPMS_TASK_FORM_RELATION(task_definition_id, form_value, entity)values('user_task_branch_banking_account_reference', '{"transactionType":[{"updatedFieldId":"accountNumber","operationType":"VALIDATION","operations":[],"references":["transactionType"],"options":{"transactionType":[{"id":"cash","value":"Бэлэн"}]}},{"updatedFieldId":"accountNumber","operationType":"REQUIRED_VALIDATION","operations":[],"references":["transactionType"],"options":{"transactionType":[{"id":"noCash","value":"Бэлэн бус"}]}},{"updatedFieldId":"accountNumber","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":null}},{"updatedFieldId":"accountName","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":null}},{"updatedFieldId":"accountBalance","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":null}},{"updatedFieldId":"accountCurrency","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":null}},{"updatedFieldId":"deductionAmount","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":null}},{"updatedFieldId":"payCutAmount","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":null}}]}', 'JSON');

INSERT INTO ERIN_BPMS_TASK_FORM_RELATION (TASK_DEFINITION_ID,FORM_VALUE, ENTITY) 
values ('user_task_branch_banking_ussd', '{"editButton":[{"updatedFieldId":"ussdPhoneNumber","operationType":"VALIDATION_TEXT_REFERENCE","operations":[],"references":["editButton"],"options":{"editButton":"editUssdInfo"}},{"updatedFieldId":"mainAccount","operationType":"VALIDATION_TEXT_REFERENCE","operations":[],"references":["editButton"],"options":{"editButton":"editUssdInfo"}}],"checkRegistration":[{"updatedFieldId":"ussdPhoneNumber","operationType":"VALIDATION_TEXT_REFERENCE","operations":[],"references":["checkRegistration"],"options":{"checkRegistration":true}},{"updatedFieldId":"mainAccount","operationType":"VALIDATION_TEXT_REFERENCE","operations":[],"references":["checkRegistration"],"options":{"checkRegistration":true}}]}', 'JSON');

INSERT INTO ERIN_BPMS_TASK_FORM_RELATION (TASK_DEFINITION_ID,FORM_VALUE, ENTITY) 
values ('user_task_branch_banking_loan_repayment', '{"loanRepaymentType":[{"updatedFieldId":"payLoanAmount","operationType":"VALIDATION","operations":[],"references":["loanRepaymentType"],"options":{"loanRepaymentType":[{"id":"closeLoan","value":"Зээл хаах"}]}}],"transactionType":[{"updatedFieldId":"accountNumber","operationType":"VALIDATION","operations":[],"references":["transactionType"],"options":{"transactionType":[{"id":"cash","value":"Бэлэн"}]}},{"updatedFieldId":"accountName","operationType":"VALIDATION","operations":[],"references":["transactionType"],"options":{"transactionType":[{"id":"noCash","value":"Бэлэн бус"}]}},{"updatedFieldId":"accountNumber","operationType":"REQUIRED_VALIDATION","operations":[],"references":["transactionType"],"options":{"transactionType":[{"id":"noCash","value":"Бэлэн бус"}]}},{"updatedFieldId":"accountNumber","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":null}},{"updatedFieldId":"accountName","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":null}},{"updatedFieldId":"accountBalance","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":null}},{"updatedFieldId":"accountCurrency","references":["transactionType"],"operations":[],"operationType":"TEXT","options":{"cash":null}}]}', 'JSON');


ALTER TABLE PROCESS ADD CREATED_USER VARCHAR(50);
ALTER TABLE PROCESS ADD PROCESS_TYPE_CATEGORY VARCHAR(50);
