name: Build Server
run-name: Build Server from branch `${{ inputs.branch }}` by @${{ github.actor }}
on:   
  workflow_dispatch:
    inputs: 
      branch:
        description: 'The branch to build'
        required: true
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ github.event.inputs.branch }}"
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "adopt"
          cache: gradle
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 5.2
          arguments: clean build --refresh-dependencies
      - uses: actions/upload-artifact@v3
        with:
          name: server-artifacts
          path: | 
            erin-bpms-xac/erin-bpms-webapp-jboss-new-core/build/libs/*
            erin-bpms-xac/erin-bpms-webapp-jboss-branch-banking/build/libs/*
          retention-days: 5
      - name: Copy war files to server over ssh
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ vars.BPMS_TEST_SERVER_HOST }}
          username: ${{ secrets.BPMS_TEST_SERVER_USER }}
          key: ${{ secrets.BPMS_TEST_SERVER_KEY }}
          source: erin-bpms-xac/erin-bpms-webapp-jboss-branch-banking/build/libs/*,erin-bpms-xac/erin-bpms-webapp-jboss-new-core/build/libs/*
          target: ~/bpms/tmp/deployments-server/
          rm: true
          strip_components: 4
      - name: Rename war files and restart docker container 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.BPMS_TEST_SERVER_HOST }}
          username: ${{ secrets.BPMS_TEST_SERVER_USER }}
          key: ${{ secrets.BPMS_TEST_SERVER_KEY }}
          script: |
            cd ~/bpms  
            docker compose stop jboss
            mv tmp/deployments-server/erin-bpms-webapp-jboss-branch-banking-* deployments-server/erin-bpms-webapp-jboss-branch-banking.war
            mv tmp/deployments-server/erin-bpms-webapp-jboss-new-core-* deployments-server/erin-bpms-webapp-jboss-new-core.war
            docker compose up -d
